"""Owner-facing ASKODOX Admin Command Center web shell."""
from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-web"])

PAGE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ASKODOX Command Center</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}
header{background:#111827;color:white;padding:18px 22px;display:flex;gap:14px;align-items:center;justify-content:space-between}
.brand{font-weight:800;font-size:20px}.sub{font-size:12px;color:#b8c2d6}.wrap{max-width:1200px;margin:auto;padding:18px}
.login,.card{background:white;border:1px solid #e2e8f0;border-radius:16px;padding:16px;box-shadow:0 3px 12px #0f172a0d}
.login{display:flex;gap:10px;margin-bottom:16px}.login input{flex:1}
input,button,select{border:1px solid #cbd5e1;border-radius:10px;padding:10px 12px}button{background:#111827;color:white;cursor:pointer}
nav{display:flex;gap:8px;overflow:auto;margin:14px 0}nav button{white-space:nowrap;background:white;color:#334155}.active{background:#2563eb!important;color:white!important}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.metric b{display:block;font-size:26px;margin-top:6px}
.panel{display:none}.panel.show{display:block}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;border-bottom:1px solid #edf2f7;padding:9px;vertical-align:top}
.status{padding:4px 8px;border-radius:99px;background:#eef2ff}
.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:8px 0}.row input,.row select{min-width:120px}
.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:12px;margin-top:12px}
.chart h3,.card h3{margin:0 0 8px;font-size:14px}.muted{color:#64748b;font-size:12px}.up{color:#15803d}.down{color:#b91c1c}
.lvl{font-size:11px;font-weight:700;padding:3px 7px;border-radius:99px;margin-right:6px}.lvl.CONFIRMED{background:#dcfce7}
.lvl.POSSIBLE_CORRELATION{background:#fef3c7}.lvl.INSUFFICIENT_EVIDENCE{background:#e2e8f0}
button.ghost{background:white;color:#111827}textarea{width:100%;border:1px solid #cbd5e1;border-radius:10px;padding:8px;font-family:monospace;font-size:12px}
.form{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}.form label{font-size:12px;color:#334155;display:flex;flex-direction:column;gap:4px}
svg text{font-size:10px;fill:#52514e}.error{color:#b91c1c}.ok{color:#15803d}
@media(max-width:650px){.login{flex-direction:column}.wrap{padding:10px}table{display:block;overflow:auto}}
</style></head><body>
<header><div><div class="brand">ASKODOX Command Center</div><div class="sub">Control · Wiring · AI · Analytics · Staff · System Health</div></div><div><a href="/admin/console" style="color:#c7d2fe;margin-right:14px">Open the new console →</a><span id="who">Not signed in</span></div></header>
<div class="wrap">
<div class="login"><input id="key" type="password" placeholder="Owner Admin Key"><button onclick="signIn()">Owner Sign in</button><span id="msg"></span></div>
<nav id="nav"></nav><main id="main"></main>
</div>
<script>
const tabs=[
["Overview","overview"],["Users","users"],["Requests","requests"],["Orders","orders"],["Listings","listings"],
["Categories","categories"],["Support","escalations"],["No Match","no-match"],["Notifications","notifications"],
["Flow traces","traces"],["Demand gaps","demand-gaps"],["API usage","api-usage"],["Returns & disputes","returns"],["Partner Hub","partners"],["Revenue Center","revenue"],["Sponsored","sponsored"],["Offers & rewards","benefits"],["Offers","growth/offers"],["Rewards","growth/rewards"],["Referrals","growth/referrals"],["Plans","growth/plans"],["Subscriptions","growth/subscriptions"],["Catalog drafts","growth/catalog-drafts"],["Staff","staff"],["Integrations","integrations"],["Partner & Revenue Hub","partner-revenue/partners"],["Video Sources","social-growth/video-sources"],["Social Videos","social-growth/videos"],["Sponsored / Boost","social-growth/campaigns"],["Partner Offers","social-growth/partner-offers"],["Scratch Rewards","social-growth/scratch-rewards"],["Affiliate Partners","integrations/affiliate-providers"],["Partner Analytics","integrations/external-commerce-analytics"],["System Health","health"],["Analytics","analytics"],["Audit","audit"]
];
let key=sessionStorage.getItem("askodox_admin_key")||""; document.querySelector("#key").value=key;
const esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function api(path,opts={}){let r=await fetch("/admin/cc/"+path,{...opts,headers:{"Content-Type":"application/json","X-ASKODOX-Admin-Key":key,...(opts.headers||{})}});if(!r.ok)throw new Error((await r.text())||r.status);return r.json()}
function nav(){document.querySelector("#nav").innerHTML=tabs.map((t,i)=>'<button onclick="loadTab(\''+t[1]+'\',this)" class="'+(i===0?"active":"")+'">'+t[0]+'</button>').join("")}
function table(items,all,open){if(!items?.length)return '<div class="card">No records yet.</div>';let cols=Object.keys(items[0]).slice(0,all?99:10);return '<div class="card" style="overflow:auto"><table><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join("")+'</tr></thead><tbody>'+items.map(r=>'<tr'+(open?' style="cursor:pointer" onclick="'+open+'('+Number(r.id)+')"':'')+'>'+cols.map(c=>'<td>'+esc(typeof r[c]==="object"?JSON.stringify(r[c]):r[c])+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'}
function overview(d){let p=d.participants||{};let vals=[["Buyers",p.buyers||0],["Sellers",p.sellers||0],["Providers",p.service_providers||0],["Active requests",d.requests?.active||0],["Active listings",d.listings?.active||0],["Support open",d.support_open||0],["No match",d.no_match_open||0],["Unread alerts",d.unread_notifications||0]];return '<div class="grid">'+vals.map(x=>'<div class="card metric">'+x[0]+'<b>'+esc(x[1])+'</b></div>').join("")+'</div>'}
async function send(path,method,body){let r=await fetch("/admin/cc/"+path,{method,headers:{"X-ASKODOX-Admin-Key":key,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});let t=await r.text();if(!r.ok)throw new Error(t||r.status);return t?JSON.parse(t):{}}
/* ---------------- Sponsored listings ---------------- */
const SPF=[["name","Campaign name"],["title","Title shown to customers"],["subtitle","Subtitle"],["destination_url","Destination URL (https)"],["image_url","Image URL (https, optional)"],["categories","Target categories (comma)","list"],["keywords","Target products / services (keywords, comma)","list"],["locations","Target locations (comma; empty = everywhere)","list"],["starts_at","Start (YYYY-MM-DD)"],["ends_at","End (YYYY-MM-DD)"],["budget","Budget ₹","num"],["cost_per_click","Cost per click ₹","num"],["cost_per_thousand","Cost per 1000 impressions ₹","num"],["priority","Priority","num"],["notes","Internal notes","ta"]];
let spCache={campaigns:[],advertisers:[]};
async function sponsoredTab(){let m=document.querySelector("#main");let [d,a]=await Promise.all([api("sponsored"),api("sponsored/analytics?days=30")]);spCache=d;let ov=a.organic_vs_sponsored||{};
m.innerHTML='<div class="card"><h3>Sponsored listings</h3><div class="muted">Paid placements are always labelled Sponsored / Promoted in the app and shown in their own section AFTER organic results -- they never change organic ranking. Only APPROVED campaigns with a category or keyword target, an https destination, inside their dates and under budget are served. Editing what an approved campaign shows sends it back to Draft. Nothing is pre-filled.</div><div class="row"><button onclick="spAdvForm()">+ Advertiser</button><button onclick="spForm()">+ Campaign</button></div></div>'+
'<div class="grid" style="margin-top:12px">'+[["Searches (30d)",ov.searches||0],["Organic results",ov.organic_results||0],["Sponsored results",ov.sponsored_results||0],["Sponsored share",ov.sponsored_share_percent==null?"—":ov.sponsored_share_percent+"%"],["Impressions",a.totals.impressions],["Clicks",a.totals.clicks],["CTR",a.totals.ctr==null?"—":a.totals.ctr+"%"],["Conversions",a.totals.conversions],["Spend ₹",a.totals.spend]].map(x=>'<div class="card metric">'+x[0]+'<b>'+esc(x[1])+'</b></div>').join("")+'</div>'+
'<div class="card" style="margin-top:12px;overflow:auto"><h3>Advertisers</h3>'+(d.advertisers.length?'<table><tr><th>Name</th><th>Kind</th><th>Contact</th><th>Status</th><th></th></tr>'+d.advertisers.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.kind)+'</td><td>'+esc(x.contact||"")+'</td><td>'+(x.active?"Active":"Disabled")+'</td><td><div class="row"><button class="ghost" onclick="spAdvForm('+x.id+')">Edit</button><button class="ghost" onclick="spAdvToggle('+x.id+','+(!x.active)+')">'+(x.active?"Disable":"Enable")+'</button></div></td></tr>').join("")+'</table>':'No advertisers yet.')+'</div>'+
'<div class="card" style="margin-top:12px;overflow:auto"><h3>Campaigns</h3>'+(d.campaigns.length?'<table><tr><th>Campaign</th><th>Kind / label</th><th>Target</th><th>Window</th><th>Budget</th><th>Status</th><th>Impr · clicks · conv · spend</th><th>Actions</th></tr>'+d.campaigns.map(c=>{let adv=d.advertisers.find(x=>x.id===c.advertiser_id);let s=c.stats||{};return '<tr><td><b>'+esc(c.name)+'</b><div class="muted">'+esc(c.title)+(adv?' · '+esc(adv.name):'')+'</div></td><td>'+esc(c.kind)+' · '+esc(c.label)+'</td><td>'+esc([(c.categories||[]).join(", "),(c.keywords||[]).join(", "),(c.locations||[]).join(", ")||"everywhere"].filter(Boolean).join(" | "))+'</td><td>'+esc((c.starts_at||"now")+" → "+(c.ends_at||"open"))+'</td><td>'+esc(c.budget==null?"no cap":"₹"+c.budget)+'</td><td>'+esc(c.status)+'</td><td>'+esc([s.impressions||0,s.clicks||0,s.conversions||0,"₹"+(s.spend||0)].join(" · "))+'</td><td><div class="row"><button class="ghost" onclick="spForm('+c.id+')">Edit</button>'+(c.status!=="APPROVED"?'<button class="ghost" onclick="spStatus('+c.id+',\'APPROVED\')">Approve</button>':'<button class="ghost" onclick="spStatus('+c.id+',\'PAUSED\')">Pause</button>')+(c.status!=="DISABLED"?'<button class="ghost" onclick="spStatus('+c.id+',\'DISABLED\')">Disable</button>':'')+'<button class="ghost" onclick="spConversion('+c.id+')">+ Conversion</button></div></td></tr>'}).join("")+'</table>':'No campaigns yet.')+'</div>'+
'<div class="card" style="margin-top:12px"><h3>Organic vs sponsored per day</h3>'+table(a.daily,true)+'</div><div id="spout"></div>'}
function spAdvForm(id){let x=spCache.advertisers.find(a=>a.id===id)||{kind:"brand"};document.querySelector("#spout").innerHTML='<div class="card" style="margin-top:12px"><h3>'+(id?"Edit advertiser":"New advertiser")+'</h3><div class="form"><label>Name<input id="sa_name" value="'+esc(x.name||"")+'"></label><label>Kind<select id="sa_kind">'+spCache.advertiser_kinds.map(k=>'<option '+(k===x.kind?"selected":"")+'>'+k+'</option>').join("")+'</select></label><label>Contact<input id="sa_contact" value="'+esc(x.contact||"")+'"></label><label>Notes<textarea id="sa_notes" rows="2">'+esc(x.notes||"")+'</textarea></label></div><div class="row"><button onclick="spAdvSave('+(id||0)+')">Save</button><span id="samsg"></span></div></div>'}
async function spAdvSave(id){try{let body={};for(let n of ["name","kind","contact","notes"])body[n]=document.querySelector("#sa_"+n).value.trim();await send(id?"sponsored/advertisers/"+id:"sponsored/advertisers",id?"PATCH":"POST",body);sponsoredTab()}catch(e){document.querySelector("#samsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
async function spAdvToggle(id,active){await send("sponsored/advertisers/"+id,"PATCH",{active});sponsoredTab()}
function spForm(id){let c=spCache.campaigns.find(x=>x.id===id)||{kind:"sponsored_listing",label:"Sponsored",placement:"chat_results"};let v=f=>{let x=c[f[0]];if(Array.isArray(x))return x.join(", ");return x??""};let sel=(n,opts,cur)=>'<select id="sp_'+n+'">'+opts.map(o=>'<option '+(String(o)===String(cur)?"selected":"")+'>'+o+'</option>').join("")+'</select>';
document.querySelector("#spout").innerHTML='<div class="card" style="margin-top:12px"><h3>'+(id?"Edit "+esc(c.name):"New campaign")+'</h3><div class="form"><label>Advertiser<select id="sp_advertiser_id"><option value="">—</option>'+spCache.advertisers.map(a=>'<option value="'+a.id+'" '+(a.id===c.advertiser_id?"selected":"")+'>'+esc(a.name)+'</option>').join("")+'</select></label><label>Kind'+sel("kind",spCache.campaign_kinds,c.kind)+'</label><label>Label'+sel("label",spCache.labels,c.label)+'</label><label>Placement'+sel("placement",spCache.placements,c.placement)+'</label>'+SPF.map(f=>'<label>'+esc(f[1])+(f[2]==="ta"?'<textarea id="sp_'+f[0]+'" rows="2">'+esc(v(f))+'</textarea>':'<input id="sp_'+f[0]+'" value="'+esc(v(f))+'">')+'</label>').join("")+'</div><div class="row"><button onclick="spSave('+(id||0)+')">Save (as draft)</button><span id="spmsg"></span></div></div>'}
async function spSave(id){try{let body={};for(let f of SPF){let x=document.querySelector("#sp_"+f[0]).value.trim();if(f[2]==="list")body[f[0]]=x?x.split(",").map(s=>s.trim()).filter(Boolean):[];else if(f[2]==="num")body[f[0]]=x===""?null:Number(x);else body[f[0]]=x}for(let n of ["kind","label","placement"])body[n]=document.querySelector("#sp_"+n).value;let adv=document.querySelector("#sp_advertiser_id").value;body.advertiser_id=adv?Number(adv):null;await send(id?"sponsored/campaigns/"+id:"sponsored/campaigns",id?"PATCH":"POST",body);sponsoredTab()}catch(e){document.querySelector("#spmsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
async function spStatus(id,status){try{await send("sponsored/campaigns/"+id+"/status","POST",{status});sponsoredTab()}catch(e){alert(e.message)}}
async function spConversion(id){let amount=prompt("Conversion value ₹ from the advertiser's report (blank if unknown)");if(amount===null)return;let note=prompt("Source / reference (e.g. report name)")||"";try{await send("sponsored/campaigns/"+id+"/conversions","POST",{amount:amount.trim()===""?null:Number(amount),note});sponsoredTab()}catch(e){alert(e.message)}}
/* ---------------- Offers & rewards ---------------- */
const BF=[["name","Campaign name"],["provider_name","Provider (bank / merchant / partner)"],["partner_id","Partner id (only for a partner's own offer)","num"],["description","Description","ta"],["categories","Eligible categories (comma; empty = all)","list"],["keywords","Eligible products / services (keywords, comma)","list"],["locations","Locations (comma)","list"],["countries","Countries (comma)","list"],["payment_methods","Payment methods (comma, e.g. Bank A credit card, UPI)","list"],["min_purchase","Minimum purchase ₹","num"],["max_discount","Maximum discount ₹","num"],["discount_amount","Discount ₹","num"],["discount_percent","Discount %","num"],["cashback_amount","Cashback ₹","num"],["cashback_percent","Cashback %","num"],["credit_amount","ASKODOX credit ₹","num"],["free_benefit","Free gift / service"],["starts_at","Start (YYYY-MM-DD)"],["ends_at","End (YYYY-MM-DD)"],["per_user_limit","Per-user limit","num"],["total_budget","Total budget ₹","num"],["total_cap","Total claims cap","num"],["partner_share_percent","Partner share % (shared funding)","num"],["priority","Priority","num"],["source_url","Source URL where the offer is published (https)"],["terms","Terms","ta"],["tracking_params","Tracking params (JSON)","json"]];
let benefitsCache=[];
async function benefitsTab(){let m=document.querySelector("#main");let [d,a]=await Promise.all([api("benefits"),api("benefits/analytics?period=30d")]);benefitsCache=d.items;window._bmeta=d;
m.innerHTML='<div class="card"><h3>Offers, coupons &amp; rewards</h3><div class="muted">Only verified offers are shown to customers: bank / UPI / merchant / partner offers need the source URL and a verification tick. Coupon codes are encrypted and revealed only to the customer who claims one. Scratch &amp; Reveal rewards are fixed per campaign (no lottery) and unlock only after a real completed order.</div><div class="row"><button onclick="benefitForm()">+ New campaign</button><button class="ghost" onclick="benefitImport()">Import (JSON)</button></div></div>'+
'<div class="card" style="margin-top:12px;overflow:auto"><h3>Campaigns</h3>'+(d.items.length?'<table><tr><th>Campaign</th><th>Type</th><th>Value</th><th>Window</th><th>Verified</th><th>Use</th><th>Actions</th></tr>'+d.items.map(c=>'<tr><td><b>'+esc(c.name)+'</b><div class="muted">'+esc(c.provider_name||"")+' · funded by '+esc(c.funding_source)+'</div></td><td>'+esc(c.offer_type)+'</td><td>'+esc([c.discount_amount!=null?"₹"+c.discount_amount:"",c.discount_percent?c.discount_percent+"%":"",c.cashback_amount!=null?"₹"+c.cashback_amount+" cashback":"",c.cashback_percent?c.cashback_percent+"% cashback":"",c.credit_amount!=null?"₹"+c.credit_amount+" credit":"",c.free_benefit||""].filter(Boolean).join(" · "))+'</td><td>'+esc((c.starts_at||"now")+" → "+(c.ends_at||"open"))+'</td><td>'+(c.verified_at?'<span class="ok">✓ '+esc(c.verified_at.slice(0,10))+'</span>':'—')+'</td><td>'+c.claims+' claims · '+c.redemptions+' redeemed · '+c.coupons_available+' codes left</td><td><div class="row"><button class="ghost" onclick="benefitForm('+c.id+')">Edit</button><button class="ghost" onclick="benefitToggle('+c.id+','+(!c.active)+')">'+(c.active?"Disable":"Enable")+'</button><button class="ghost" onclick="benefitCodes('+c.id+')">Add codes</button></div></td></tr>').join("")+'</table>':'No campaigns yet.')+'</div>'+
'<div class="card" style="margin-top:12px"><h3>Last 30 days</h3>'+table(a.items,true)+'<div class="muted">Totals: '+esc(JSON.stringify(a.totals))+'. ROI is shown only where revenue can be attributed to a campaign.</div></div><div id="bout"></div>'}
function benefitForm(id){let c=benefitsCache.find(x=>x.id===id)||{active:false,offer_type:"coupon",funding_source:"askodox",source_kind:"admin_entered"};let v=f=>{let x=c[f[0]];if(f[2]==="json")return x&&Object.keys(x).length?JSON.stringify(x):"";if(Array.isArray(x))return x.join(", ");return x??""};let sel=(n,opts,cur)=>'<select id="bf_'+n+'">'+opts.map(o=>'<option '+(o===cur?"selected":"")+'>'+o+'</option>').join("")+'</select>';
document.querySelector("#bout").innerHTML='<div class="card" style="margin-top:12px"><h3>'+(id?"Edit "+esc(c.name):"New campaign")+'</h3><div class="form"><label>Offer type'+sel("offer_type",window._bmeta.offer_types,c.offer_type)+'</label><label>Funded by'+sel("funding_source",window._bmeta.funding_sources,c.funding_source)+'</label><label>Source kind'+sel("source_kind",window._bmeta.source_kinds,c.source_kind)+'</label>'+BF.map(f=>'<label>'+esc(f[1])+(f[2]==="ta"?'<textarea id="bf_'+f[0]+'" rows="3">'+esc(v(f))+'</textarea>':'<input id="bf_'+f[0]+'" value="'+esc(v(f))+'">')+'</label>').join("")+'<label><span><input type="checkbox" id="bf_verified"> I verified this offer at the source just now</span></label><label>Active<select id="bf_active"><option value="false">Inactive</option><option value="true" '+(c.active?"selected":"")+'>Active</option></select></label></div><div class="row"><button onclick="benefitSave('+(id||0)+')">Save</button><span id="bmsg"></span></div></div>'}
async function benefitSave(id){let body={};try{for(let f of BF){let x=document.querySelector("#bf_"+f[0]).value.trim();if(!x)continue;if(f[2]==="num")body[f[0]]=Number(x);else if(f[2]==="list")body[f[0]]=x.split(",").map(s=>s.trim()).filter(Boolean);else if(f[2]==="json")body[f[0]]=JSON.parse(x);else body[f[0]]=x}for(let n of ["offer_type","funding_source","source_kind"])body[n]=document.querySelector("#bf_"+n).value;if(document.querySelector("#bf_verified").checked)body.verified=true;body.active=document.querySelector("#bf_active").value==="true";await send(id?"benefits/"+id:"benefits",id?"PATCH":"POST",body);benefitsTab()}catch(e){document.querySelector("#bmsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
async function benefitToggle(id,active){await send("benefits/"+id,"PATCH",{active});benefitsTab()}
function benefitCodes(id){document.querySelector("#bout").innerHTML='<div class="card" style="margin-top:12px"><h3>Add coupon codes (one per line)</h3><textarea id="bcodes" rows="8"></textarea><div class="row"><button onclick="benefitCodesGo('+id+')">Add</button><span id="bmsg"></span></div></div>'}
async function benefitCodesGo(id){try{let r=await send("benefits/"+id+"/coupons","POST",{codes:document.querySelector("#bcodes").value.split(/\n+/).map(s=>s.trim()).filter(Boolean)});document.querySelector("#bmsg").innerHTML='<span class="ok">'+r.added+' added</span>, '+r.skipped+' skipped (duplicates / invalid)'}catch(e){document.querySelector("#bmsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
function benefitImport(){document.querySelector("#bout").innerHTML='<div class="card" style="margin-top:12px"><h3>Import campaigns (JSON list, same fields as the form)</h3><div class="muted">E.g. from a partner\'s verified offer export. Each row is validated; invalid rows are reported.</div><textarea id="bjson" rows="10">[]</textarea><div class="row"><button onclick="benefitImportGo()">Import</button><span id="bmsg"></span></div></div>'}
async function benefitImportGo(){try{let r=await send("benefits/import","POST",{campaigns:JSON.parse(document.querySelector("#bjson").value)});document.querySelector("#bmsg").innerHTML='<span class="ok">'+r.created.length+' created</span> '+(r.errors.length?'<span class="error">'+esc(JSON.stringify(r.errors))+'</span>':'');benefitsTab()}catch(e){document.querySelector("#bmsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
/* ---------------- Flow traces ---------------- */
async function tracesTab(){let m=document.querySelector("#main");if(!document.querySelector("#tf_q")){m.innerHTML='<div class="card"><h3>Flow traces</h3><div class="muted">One row per customer request: language, intent, role, categories, slots, location, sources (ASKODOX / nearby / partner / web), filtered + reasons, ranking, clicks, actions, sign-in interruption / resume, deal / order id, outcome. User ids are masked; phone numbers and e-mails in text are redacted. Click a row for every step.</div><div class="row"><input id="tf_q" placeholder="search query / category / result"><input id="tf_language" placeholder="language (te, hi, en…)"><select id="tf_outcome"><option value="">any outcome</option><option>action_ok</option><option>action_failed</option><option>partner_click</option><option>partner_opened</option><option>results_sent</option><option>no_results</option><option>error</option></select><select id="tf_source"><option value="">any source</option><option>registered</option><option>nearby</option><option>partner</option><option>online</option><option>videos</option></select><input id="tf_deal_id" placeholder="deal id" style="min-width:80px"><input id="tf_since" type="date"><input id="tf_until" type="date"><label class="muted"><input id="tf_errors" type="checkbox"> errors only</label><button onclick="tracesTab()">Filter</button></div></div><div id="tout"></div>'}
let q=new URLSearchParams({limit:"200"});for(let f of ["q","language","outcome","source","deal_id","since","until"]){let v=document.querySelector("#tf_"+f).value;if(v)q.set(f,v)}if(document.querySelector("#tf_errors").checked)q.set("errors_only","true");
let d=await api("traces?"+q.toString());document.querySelector("#tout").innerHTML='<div class="muted" style="margin:8px 0">'+d.items.length+' trace(s)</div>'+table(d.items,true,"traceDetail")}
/* ---------------- Partner Hub ---------------- */
const PF=[["name","Name"],["logo_url","Logo URL (https)"],["categories","Categories (comma; empty = all)"],["countries","Countries (comma, e.g. IN)"],["locations","Locations (comma; empty = all)"],["signup_url","Affiliate program signup URL"],["tracking_id","Tracking / tag ID"],["deep_link_template","Deep-link template ({query} {url} {tracking_id} {sub_id} {campaign})"],["base_url","Base URL (fallback)"],["sub_id_param","Sub-ID parameter name"],["apply_instructions","How / where to apply","ta"],["link_instructions","Where to get the link / tracking ID","ta"],["campaign_params","Campaign params (JSON)","json"],["feed","Product feed/API (JSON, optional)","json"],["commission","Commission rule (JSON)","json"],["webhook_notes","Postback / webhook notes","ta"],["attribution_notes","Attribution / cookie notes","ta"],["notes","Notes","ta"]];
let partnersCache=[];
async function partnersTab(){let m=document.querySelector("#main");let [d,g,sec]=await Promise.all([api("partners"),api("partners/guide"),api("partners/security")]);partnersCache=d.items;
m.innerHTML='<div class="card"><h3>Affiliate / Partner Hub</h3><div class="muted">Any company, any category. Secrets are write-only and stay on the server; the app never receives them. '+esc(g.note)+'</div>'+
'<details style="margin-top:8px"><summary><b>What you need, where to get it, where to paste it</b></summary><table><tr><th>Level</th><th>Needs</th><th>Gives</th></tr>'+g.levels.map(l=>'<tr><td>'+l.level+'. '+esc(l.name)+'</td><td>'+esc(l.needs)+'</td><td>'+esc(l.gives)+'</td></tr>').join("")+'</table><table style="margin-top:8px"><tr><th>Field</th><th>Where to get it</th></tr>'+g.fields.map(f=>'<tr><td>'+esc(f.field)+'</td><td>'+esc(f.where)+'</td></tr>').join("")+'</table></details>'+
'<div class="row"><button onclick="partnerForm()">+ Add partner</button><button class="ghost" onclick="partnerRotate()">Re-encrypt keys</button></div><div class="muted">Security: '+(sec.secrets_key_configured?'<span class="ok">✓ keys encrypted (ASKODOX_SECRETS_KEY set)</span>':'<span class="error">✗ ASKODOX_SECRETS_KEY not set — keys cannot be saved</span>')+' · click events accepted for '+sec.click_ttl_hours+' h · raw events kept '+sec.event_retention_days+' days, then rolled up per day (last run: '+esc(sec.retention_last_run||"never")+')</div></div>'+
(d.items.length?'<div class="card" style="overflow:auto;margin-top:12px"><table><tr><th>Partner</th><th>Status</th><th>Level</th><th>Categories</th><th>Keys</th><th>Last check</th><th>Actions</th></tr>'+d.items.map(p=>'<tr><td><b>'+esc(p.name)+'</b><div class="muted">'+esc(p.slug)+'</div></td><td>'+(p.active?'<span class="ok">● Active</span>':'○ Inactive')+'</td><td>'+p.capabilities.highest_level+'<div class="muted">measures: '+esc(p.capabilities.measurable.join(", ")||"nothing yet")+'</div></td><td>'+esc((p.categories||[]).join(", ")||"all")+'</td><td>'+esc(Object.keys(p.secrets).map(k=>k+" ✓").join(", ")||"none")+'</td><td>'+(p.last_check_at?(p.last_check_ok?'<span class="ok">✓ OK</span>':'<span class="error">✗ '+esc(p.last_error)+'</span>')+'<div class="muted">'+esc(p.last_check_at)+(p.last_sync_at?' · last sync '+esc(p.last_sync_at):'')+'</div>':'never')+'</td><td><div class="row"><button class="ghost" onclick="partnerForm('+p.id+')">Edit</button><button class="ghost" onclick="partnerTest('+p.id+')">Test</button><button class="ghost" onclick="partnerToggle('+p.id+','+(!p.active)+')">'+(p.active?"Disable":"Enable")+'</button><button class="ghost" onclick="partnerSecret('+p.id+')">Set key</button><button class="ghost" onclick="partnerPostback('+p.id+')">Postback URL</button><button class="ghost" onclick="partnerImport('+p.id+')">Import report</button></div></td></tr>').join("")+'</table></div>':'<div class="card" style="margin-top:12px">No partners yet. Add one with the button above.</div>')+'<div id="pout"></div>'}
function partnerForm(id){let p=partnersCache.find(x=>x.id===id)||{active:false};let v=f=>{let x=p[f[0]];if(f[2]==="json")return x&&Object.keys(x).length?JSON.stringify(x,null,1):"";if(Array.isArray(x))return x.join(", ");return x??""};
document.querySelector("#pout").innerHTML='<div class="card" style="margin-top:12px"><h3>'+(id?"Edit "+esc(p.name):"New partner")+'</h3><div class="form">'+PF.map(f=>'<label>'+esc(f[1])+(f[2]?'<textarea id="pf_'+f[0]+'" rows="3">'+esc(v(f))+'</textarea>':'<input id="pf_'+f[0]+'" value="'+esc(v(f))+'">')+'</label>').join("")+'<label>Active<select id="pf_active"><option value="false">Inactive</option><option value="true" '+(p.active?"selected":"")+'>Active</option></select></label></div><div class="row"><button onclick="partnerSave('+(id||0)+')">Save</button><span id="pmsg"></span></div></div>'}
async function partnerSave(id){let body={};try{for(let f of PF){let x=document.querySelector("#pf_"+f[0]).value.trim();if(f[2]==="json")body[f[0]]=x?JSON.parse(x):{};else if(["categories","countries","locations"].includes(f[0]))body[f[0]]=x?x.split(",").map(s=>s.trim()).filter(Boolean):[];else body[f[0]]=x}body.active=document.querySelector("#pf_active").value==="true";await send(id?"partners/"+id:"partners",id?"PATCH":"POST",body);partnersTab()}catch(e){document.querySelector("#pmsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
async function partnerRotate(){if(!confirm("Re-encrypt all stored partner keys with the current ASKODOX_SECRETS_KEY?"))return;try{let r=await send("partners/secrets/rotate","POST");alert(r.rewritten+" re-encrypted, "+r.unreadable+" unreadable");partnersTab()}catch(e){alert(e.message)}}
async function partnerToggle(id,active){await send("partners/"+id,"PATCH",{active});partnersTab()}
async function partnerTest(id){let r=await send("partners/"+id+"/test","POST");document.querySelector("#pout").innerHTML='<div class="card" style="margin-top:12px"><h3>Integration test: '+(r.ok?'<span class="ok">✓ works</span>':'<span class="error">✗ needs attention</span>')+'</h3>'+table(r.checks,true)+(r.missing.length?'<h3 style="margin-top:8px">Missing</h3>'+table(r.missing,true):'')+'</div>'}
async function partnerSecret(id){let name=prompt("Which key? api_key, api_secret, feed_token","api_key");if(!name)return;let value=prompt("Paste the value (stored on the server only; leave empty to remove)")??"";try{await send("partners/"+id+"/secrets/"+name,"PUT",{value});partnersTab()}catch(e){alert(e.message)}}
async function partnerPostback(id){if(!confirm("Generate a new postback token? The old one stops working."))return;let r=await send("partners/"+id+"/postback-token","POST");document.querySelector("#pout").innerHTML='<div class="card" style="margin-top:12px"><h3>Paste this into the partner dashboard (postback / conversion URL)</h3><textarea rows="3" readonly>'+esc(r.postback_url)+'</textarea><div class="muted">'+esc(r.note)+' Replace {order_id}, {amount}, {payout}, {status}, {sub_id} with the partner\'s own macros.</div></div>'}
function partnerImport(id){document.querySelector("#pout").innerHTML='<div class="card" style="margin-top:12px"><h3>Import partner report (CSV)</h3><div class="muted">Columns: order_id, click_id or sub_id, order_value, commission, status, date, currency. Rows update earlier imports/postbacks.</div><textarea id="pcsv" rows="8"></textarea><div class="row"><button onclick="partnerImportGo('+id+')">Import</button><span id="pmsg"></span></div></div>'}
async function partnerImportGo(id){try{let r=await send("partners/"+id+"/import","POST",{csv:document.querySelector("#pcsv").value});document.querySelector("#pmsg").innerHTML='<span class="ok">'+r.imported+' imported</span> '+(r.errors.length?'<span class="error">'+r.errors.length+' row(s) rejected: '+esc(JSON.stringify(r.errors.slice(0,5)))+'</span>':'')}catch(e){document.querySelector("#pmsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
/* ---------------- Revenue Center ---------------- */
const INR=n=>n==null?"—":"₹"+Number(n).toLocaleString("en-IN",{maximumFractionDigits:2});const NUM=n=>n==null?"—":Number(n).toLocaleString("en-IN");
const KPI=[["total_revenue","Total ASKODOX revenue",INR],["searches","Searches",NUM],["impressions","Partner impressions",NUM],["clicks","Clicks",NUM],["ctr_pct","CTR %",NUM],["leads","Leads",NUM],["orders","Orders",NUM],["conversion_rate_pct","Conversion %",NUM],["gmv","GMV / order value",INR],["expected_commission","Expected commission",INR],["confirmed_commission","Confirmed commission",INR],["pending_commission","Pending commission",INR],["paid_commission","Paid commission",INR],["reversed_commission","Reversed",INR],["rejected_commission","Rejected",INR],["other_revenue","Other revenue (entries)",INR],["reward_cost_askodox","Reward cost (ASKODOX)",INR],["reward_cost_partner","Reward cost (partners)",INR],["net_revenue","Net revenue after rewards",INR],["reward_redemptions","Rewards redeemed",NUM],["offer_opens","Offer terms opened",NUM]];
function rq(){let q=new URLSearchParams();for(let f of ["period","start","end","partner","category","location","campaign","language"]){let el=document.querySelector("#rf_"+f);if(el&&el.value)q.set(f,el.value)}return q.toString()}
const BAD_UP=["reversed_commission","rejected_commission","reward_cost_askodox"];
function delta(c,k){if(c==null)return '<span class="muted">no previous data</span>';if(c===0)return '<span class="muted">■ no change</span>';let good=(c>0)!==BAD_UP.includes(k);return '<span class="'+(good?"up":"down")+'">'+(c>0?"▲ ":"▼ ")+Math.abs(c)+'% vs previous</span>'}
function hbars(rows,label,val,fmt,onclick){rows=rows.filter(r=>(r[val]||0)>0);if(!rows.length)return '<div class="muted">No records in this period.</div>';let max=Math.max(...rows.map(r=>r[val]||0)),h=22,w=250;return '<svg viewBox="0 0 '+(w+150)+' '+(rows.length*h+4)+'" width="100%" role="img">'+rows.slice(0,10).map((r,i)=>{let bw=Math.max(2,(r[val]||0)/max*w);return '<g'+(onclick?' style="cursor:pointer" onclick="'+onclick+'(\''+esc(r[label]).replace(/'/g,"")+'\')"':'')+'><title>'+esc(r[label])+': '+fmt(r[val])+'</title><text x="0" y="'+(i*h+15)+'">'+esc(String(r[label]).slice(0,20))+'</text><rect x="120" y="'+(i*h+4)+'" width="'+bw+'" height="14" rx="4" fill="#2a78d6"/><text x="'+(124+bw)+'" y="'+(i*h+15)+'">'+fmt(r[val])+'</text></g>'}).join("")+'</svg>'}
function columns(series,val,fmt){if(!series.length)return '';let max=Math.max(1,...series.map(r=>r[val]||0)),w=460,h=150,bw=Math.max(3,w/series.length-2);return '<svg viewBox="0 0 '+w+' '+(h+20)+'" width="100%" role="img"><line x1="0" y1="'+h+'" x2="'+w+'" y2="'+h+'" stroke="#e2e8f0"/>'+series.map((r,i)=>{let bh=(r[val]||0)/max*(h-10);return '<g><title>'+r.day+': '+fmt(r[val]||0)+'</title><rect x="'+(i*(bw+2))+'" y="'+(h-bh)+'" width="'+bw+'" height="'+Math.max(bh,0)+'" rx="3" fill="#2a78d6"/><rect x="'+(i*(bw+2))+'" y="0" width="'+bw+'" height="'+h+'" fill="transparent"/></g>'}).join("")+'<text x="0" y="'+(h+14)+'">'+series[0].day+'</text><text x="'+(w-60)+'" y="'+(h+14)+'">'+series[series.length-1].day+'</text><text x="0" y="10">max '+fmt(max)+'</text></svg>'}
function line(series,val,fmt){if(series.length<2)return columns(series,val,fmt);let max=Math.max(1,...series.map(r=>r[val]||0)),w=460,h=150,x=i=>i*(w/(series.length-1)),y=v=>h-(v||0)/max*(h-10);let pts=series.map((r,i)=>x(i)+","+y(r[val])).join(" ");return '<svg viewBox="0 0 '+w+' '+(h+20)+'" width="100%" role="img"><line x1="0" y1="'+h+'" x2="'+w+'" y2="'+h+'" stroke="#e2e8f0"/><polyline points="'+pts+'" fill="none" stroke="#2a78d6" stroke-width="2"/>'+series.map((r,i)=>'<g><title>'+r.day+': '+fmt(r[val]||0)+'</title><circle cx="'+x(i)+'" cy="'+y(r[val])+'" r="4" fill="#2a78d6" stroke="white" stroke-width="2"/><rect x="'+(x(i)-8)+'" y="0" width="16" height="'+h+'" fill="transparent"/></g>').join("")+'<text x="0" y="'+(h+14)+'">'+series[0].day+'</text><text x="'+(w-60)+'" y="'+(h+14)+'">'+series[series.length-1].day+'</text><text x="0" y="10">max '+fmt(max)+'</text></svg>'}
function funnel(f){let top=Math.max(1,f[0].count);return '<svg viewBox="0 0 470 '+(f.length*26)+'" width="100%" role="img">'+f.map((s,i)=>{let w=Math.max(2,s.count/Math.max(...f.map(x=>x.count),1)*300);let prev=i?f[i-1].count:null;return '<g><title>'+s.stage+': '+NUM(s.count)+'</title><text x="0" y="'+(i*26+16)+'">'+s.stage+'</text><rect x="110" y="'+(i*26+4)+'" width="'+w+'" height="16" rx="4" fill="#2a78d6"/><text x="'+(116+w)+'" y="'+(i*26+16)+'">'+NUM(s.count)+(prev?' ('+(s.count/prev*100).toFixed(1)+'% of previous)':'')+'</text></g>'}).join("")+'</svg>'}
function setFilter(k,v){document.querySelector("#rf_"+k).value=v;revenueLoad()}
async function revenueTab(){document.querySelector("#main").innerHTML='<div class="card"><h3>Revenue Center</h3><div class="row"><select id="rf_period" onchange="document.querySelector(\'#custom\').style.display=this.value===\'custom\'?\'flex\':\'none\'"><option value="today">Today</option><option value="7d" selected>7 days</option><option value="30d">30 days</option><option value="month">This month</option><option value="custom">Custom</option></select><span id="custom" class="row" style="display:none;margin:0"><input id="rf_start" type="date"><input id="rf_end" type="date"></span><input id="rf_partner" placeholder="partner slug"><input id="rf_category" placeholder="category"><input id="rf_location" placeholder="location"><input id="rf_campaign" placeholder="campaign"><input id="rf_language" placeholder="language"><button onclick="revenueLoad()">Apply</button><select id="rf_kind"><option value="daily">Daily CSV</option><option value="conversions">Conversions CSV</option><option value="events">Events CSV</option><option value="entries">Entries CSV</option></select><button class="ghost" onclick="revenueExport()">Export</button></div><div class="muted">Times in India (Asia/Kolkata). Click a partner or category bar to filter.</div></div><div id="rout"></div>';revenueLoad()}
async function revenueLoad(){let o=document.querySelector("#rout");o.innerHTML='<div class="card">Loading real data…</div>';try{let d=await api("revenue?"+rq());let m=d.metrics,c=d.change_pct,b=d.breakdowns;
let comm=[["Pending",m.pending_commission],["Confirmed",m.confirmed_commission],["Paid",m.paid_commission],["Rejected",m.rejected_commission],["Reversed",m.reversed_commission]].map(x=>({k:x[0],v:x[1]}));
o.innerHTML='<div class="grid" style="margin-top:12px">'+KPI.map(k=>'<div class="card metric">'+k[1]+'<b>'+k[2](m[k[0]])+'</b>'+delta(c[k[0]],k[0])+'</div>').join("")+'</div>'+
'<div class="charts"><div class="card chart"><h3>Revenue trend (per day)</h3>'+line(d.series,"revenue",INR)+'</div><div class="card chart"><h3>Sales (orders per day)</h3>'+columns(d.series,"orders",NUM)+'</div>'+
'<div class="card chart"><h3>Click → lead → sale funnel</h3>'+funnel(d.funnel)+'</div><div class="card chart"><h3>Commission breakdown</h3>'+hbars(comm,"k","v",INR)+'</div>'+
'<div class="card chart"><h3>Partner comparison (revenue)</h3>'+hbars(b.partner,"key","revenue",INR)+'<h3 style="margin-top:8px">Partner clicks</h3>'+hbars(b.partner,"key","clicks",NUM)+'</div><div class="card chart"><h3>Category comparison (revenue)</h3>'+hbars(b.category,"key","revenue",INR,"catFilter")+'<h3 style="margin-top:8px">Category searches</h3>'+hbars(b.category,"key","searches",NUM,"catFilter")+'</div></div>'+
'<div class="card" style="margin-top:12px"><h3>Why up / down?</h3><div class="muted">Compares with the previous '+d.period.days+' day(s). Only recorded data; CONFIRMED vs POSSIBLE CORRELATION vs INSUFFICIENT EVIDENCE.</div><button onclick="revenueWhy()">Explain this period</button><div id="why"></div></div>'+
'<div class="card" style="margin-top:12px"><h3>Breakdowns (table view)</h3><div class="row"><select id="rb" onchange="document.querySelector(\'#rbt\').innerHTML=table(window._rb[this.value],true)">'+Object.keys(b).map(k=>'<option>'+k+'</option>').join("")+'</select></div><div id="rbt">'+table(b.source,true)+'</div></div>'+
'<div class="card" style="margin-top:12px"><h3>Records (drill-down)</h3><div class="row"><select id="rk"><option>conversions</option><option>events</option><option>entries</option></select><button class="ghost" onclick="revenueRecords()">Show</button></div><div id="rrec"></div></div>'+
'<div class="card" style="margin-top:12px"><h3>Record revenue (other sources)</h3><div class="muted">Real revenue only — e.g. a subscription paid offline, a lead fee, an ad booking. Subscriptions without a gateway (PENDING_PAYMENT) are not revenue: '+esc(JSON.stringify(d.subscriptions.by_status||{}))+'</div><div class="row"><select id="re_source">'+["subscription","lead_fee","service_fee","promotion","advertising","transaction_fee","partner_revenue","other"].map(x=>'<option>'+x+'</option>').join("")+'</select><input id="re_amount" type="number" placeholder="amount ₹"><input id="re_reference" placeholder="reference (UPI / invoice)"><input id="re_note" placeholder="note"><button onclick="revenueEntry()">Add</button><span id="remsg"></span></div></div>'+
'<div class="card muted" style="margin-top:12px">'+d.measurement_notes.map(esc).join("<br>")+'</div>';window._rb=b;
window.catFilter=v=>setFilter("category",v==="(not set)"?"":v)}catch(e){o.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}}
async function revenueWhy(){let w=document.querySelector("#why");w.innerHTML="Analysing…";let d=await api("revenue/why?"+rq());w.innerHTML='<p><b>Revenue '+d.direction+'</b> ('+INR(d.revenue_delta)+' vs previous period)</p>'+d.findings.map(f=>'<div style="margin:6px 0"><span class="lvl '+f.level+'">'+f.level.replace(/_/g," ")+'</span>'+esc(f.statement)+'<details><summary class="muted">data</summary><pre style="white-space:pre-wrap;font-size:11px">'+esc(JSON.stringify(f.data,null,1))+'</pre></details></div>').join("")+'<h3 style="margin-top:8px">Facts</h3>'+table(d.facts,true)+'<div class="muted">'+esc(d.method)+'</div>'}
async function revenueRecords(){let d=await api("revenue/records?kind="+document.querySelector("#rk").value+"&"+rq());document.querySelector("#rrec").innerHTML=table(d.items,true)}
async function revenueExport(){let r=await fetch("/admin/cc/revenue/export.csv?kind="+document.querySelector("#rf_kind").value+"&"+rq(),{headers:{"X-ASKODOX-Admin-Key":key}});if(!r.ok){alert(await r.text());return}let a=document.createElement("a");a.href=URL.createObjectURL(await r.blob());a.download="askodox-revenue.csv";a.click()}
async function revenueEntry(){try{await send("revenue/entries","POST",{source:document.querySelector("#re_source").value,amount:Number(document.querySelector("#re_amount").value),reference:document.querySelector("#re_reference").value,note:document.querySelector("#re_note").value});revenueLoad()}catch(e){document.querySelector("#remsg").innerHTML='<span class="error">'+esc(e.message)+'</span>'}}
let affiliateItems=[];
function affiliateForm(items=[]){affiliateItems=items;let rows=table(items,true,"editAffiliate");return '<div class="card"><h3>Affiliate / API / Deep-link Partners</h3><p>Configure each partner once. API is optional; when it is off or unavailable ASKODOX can use the deep-link and affiliate/web fallback.</p><div class="grid"><input id="ap_id" placeholder="Provider ID e.g. amazon"><input id="ap_name" placeholder="Provider name"><input id="ap_cat" placeholder="Category e.g. product"><input id="ap_normal" placeholder="Normal web URL"><input id="ap_aff" placeholder="Affiliate URL / {query} template"><input id="ap_deep" placeholder="App / deep link / {query} template"><input id="ap_api" placeholder="HTTPS API URL / {query} template"><input id="ap_hosts" placeholder="Allowed API hosts, comma-separated"><select id="ap_api_on"><option value="false">API disabled</option><option value="true">API enabled</option></select><input id="ap_callback" placeholder="Callback / webhook URL"><select id="ap_callback_on"><option value="false">Callback disabled</option><option value="true">Callback enabled</option></select><input id="ap_tracking" placeholder="Tracking template / campaign reference"><input id="ap_gateway" placeholder="Gateway type" value="external"><input id="ap_disc" placeholder="Disclosure" value="Affiliate link"><select id="ap_active"><option value="true">Partner active</option><option value="false">Partner disabled</option></select><button onclick="saveAffiliate()">Save partner</button></div><div id="ap_msg"></div></div>'+rows}
function editAffiliate(id){let p=affiliateItems.find(x=>String(x.provider_id||"")===String(id));if(!p)return;let set=(q,v)=>{let e=document.querySelector(q);if(e)e.value=v==null?"":String(v)};set("#ap_id",p.provider_id);set("#ap_name",p.name);set("#ap_cat",p.category);set("#ap_normal",p.normal_url);set("#ap_aff",p.affiliate_url);set("#ap_deep",p.deep_link);set("#ap_api",p.api_base_url);set("#ap_hosts",p.api_allowed_hosts);set("#ap_api_on",p.api_enabled===true?"true":"false");set("#ap_callback",p.callback_url);set("#ap_callback_on",p.callback_enabled===true?"true":"false");set("#ap_tracking",p.tracking_template);set("#ap_gateway",p.gateway||"external");set("#ap_disc",p.disclosure||"Affiliate link");set("#ap_active",p.active===true?"true":"false");document.querySelector("#ap_id").scrollIntoView({behavior:"smooth",block:"center"});document.querySelector("#ap_msg").innerHTML='<p class="ok">Editing '+esc(p.name||p.provider_id)+'</p>'}
async function saveAffiliate(){let id=document.querySelector("#ap_id").value.trim().toLowerCase();if(!id){document.querySelector("#ap_msg").innerHTML='<p class="error">Provider ID is required.</p>';return}let body={name:document.querySelector("#ap_name").value.trim(),category:document.querySelector("#ap_cat").value.trim()||"general",normal_url:document.querySelector("#ap_normal").value.trim(),affiliate_url:document.querySelector("#ap_aff").value.trim(),deep_link:document.querySelector("#ap_deep").value.trim(),api_base_url:document.querySelector("#ap_api").value.trim(),api_allowed_hosts:document.querySelector("#ap_hosts").value.trim(),api_enabled:document.querySelector("#ap_api_on").value==="true",callback_url:document.querySelector("#ap_callback").value.trim(),callback_enabled:document.querySelector("#ap_callback_on").value==="true",tracking_template:document.querySelector("#ap_tracking").value.trim(),gateway:document.querySelector("#ap_gateway").value.trim()||"external",disclosure:document.querySelector("#ap_disc").value.trim()||"Affiliate link",active:document.querySelector("#ap_active").value==="true"};try{await api("integrations/affiliate-providers/"+encodeURIComponent(id),{method:"PUT",body:JSON.stringify(body)});document.querySelector("#ap_msg").innerHTML='<p class="ok">Saved.</p>';loadTab("integrations/affiliate-providers")}catch(e){document.querySelector("#ap_msg").innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
let partnerHubItems=[];
function partnerHubForm(items=[]){partnerHubItems=items;return '<div class="card"><h3>Partner & Revenue Hub</h3><p>One control point for API, affiliate/referral, deep link, staff fallback and BFSI partners. Keep partners disabled until commercial/technical details are verified.</p><div class="grid"><input id="ph_id" placeholder="Partner ID"><input id="ph_name" placeholder="Partner name"><input id="ph_sector" placeholder="Sector e.g. commerce / insurance"><input id="ph_cat" placeholder="Category"><input id="ph_modes" placeholder="Modes: api,affiliate,referral,manual"><input id="ph_model" placeholder="Commercial model"><select id="ph_active"><option value="false">Disabled</option><option value="true">Active</option></select><button onclick="savePartnerHub()">Save partner</button></div><div id="ph_msg"></div></div>'+table(items,true)}
async function savePartnerHub(){let id=document.querySelector("#ph_id").value.trim().toLowerCase();if(!id){document.querySelector("#ph_msg").innerHTML='<p class="error">Partner ID is required.</p>';return}let body={name:document.querySelector("#ph_name").value.trim()||id,sector:document.querySelector("#ph_sector").value.trim()||"general",category:document.querySelector("#ph_cat").value.trim()||"general",integration_modes:document.querySelector("#ph_modes").value.split(",").map(x=>x.trim()).filter(Boolean),commercial_model:document.querySelector("#ph_model").value.trim()||"none",active:document.querySelector("#ph_active").value==="true"};try{await api("partner-revenue/partners/"+encodeURIComponent(id),{method:"PUT",body:JSON.stringify(body)});document.querySelector("#ph_msg").innerHTML='<p class="ok">Saved.</p>';loadTab("partner-revenue/partners")}catch(e){document.querySelector("#ph_msg").innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
async function loadTab(path,btn){document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));if(btn)btn.classList.add("active");let m=document.querySelector("#main");if(path==="sponsored"){try{await sponsoredTab()}catch(e){m.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}return}if(path==="benefits"){try{await benefitsTab()}catch(e){m.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}return}if(path==="traces"){try{await tracesTab()}catch(e){m.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}return}if(path==="partners"||path==="revenue"){try{await (path==="partners"?partnersTab():revenueTab())}catch(e){m.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}return}m.innerHTML='<div class="card">Loading real data…</div>';try{let d=await api(path);m.innerHTML=path==="integrations/affiliate-providers"?affiliateForm(d.items):path==="partner-revenue/partners"?partnerHubForm(d.items):path==="overview"?overview(d):path==="traces"?'<div class="card">Click a trace for every step (sources, filtered reasons, fallback, auth gate, seller request, escalation, timeline).</div>'+table(d.items,true,"traceDetail"):table(d.items||Object.entries(d).map(([k,v])=>({section:k,value:typeof v==="object"?JSON.stringify(v):v})))}catch(e){m.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}}
async function traceDetail(id){let m=document.querySelector("#main");try{let d=await api("traces/"+id);m.innerHTML='<div class="card"><button onclick="loadTab(\'traces\')">← All traces</button></div>'+table(Object.entries(d).map(([k,v])=>({field:k,value:typeof v==="object"?JSON.stringify(v):v})),true)}catch(e){m.innerHTML='<div class="card error">Could not load: '+esc(e.message)+'</div>'}}
async function signIn(){key=document.querySelector("#key").value.trim();sessionStorage.setItem("askodox_admin_key",key);try{let d=await api("me");document.querySelector("#who").textContent=d.name+" · "+d.role;document.querySelector("#msg").innerHTML='<span class="ok">Connected</span>';loadTab("overview",document.querySelector("nav button"))}catch(e){document.querySelector("#msg").innerHTML='<span class="error">Sign-in failed</span>'}}
nav(); if(key)signIn(); else loadTab("overview",document.querySelector("nav button"));
</script></body></html>'''

@router.get("/admin", response_class=HTMLResponse, include_in_schema=False)
@router.get("/admin/", response_class=HTMLResponse, include_in_schema=False)
def admin_web() -> HTMLResponse:
    return HTMLResponse(PAGE)
