import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../domain/analytics_models.dart';

class MetricTrendCard extends StatelessWidget { const MetricTrendCard({required this.metric,super.key}); final MetricValue metric; @override Widget build(BuildContext context){final up=metric.trend==MetricTrend.increasing; return Semantics(label:'${metric.label}, ${metric.current}, ${metric.percentageChange.toStringAsFixed(1)} percent change',child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(metric.label),const Spacer(),Text('${metric.unit}${metric.current.toStringAsFixed(metric.current%1==0?0:1)}',style:Theme.of(context).textTheme.headlineSmall),Row(children:[Icon(metric.trend==MetricTrend.stable?Icons.remove:up?Icons.trending_up:Icons.trending_down,size:18,color:metric.trend==MetricTrend.stable?Colors.grey:up?Colors.green:Colors.red),Text(' ${metric.percentageChange.abs().toStringAsFixed(1)}% vs previous')])]))));}}
class SimpleBarChart extends StatelessWidget { const SimpleBarChart({required this.values,required this.summary,super.key}); final List<double> values; final String summary; @override Widget build(BuildContext context){final max=values.fold<double>(1,(a,b)=>math.max(a,b));return Semantics(label:summary,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(height:130,child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[for(final v in values) Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:Container(height:120*v/max,decoration:BoxDecoration(color:Theme.of(context).colorScheme.primaryContainer,borderRadius:const BorderRadius.vertical(top:Radius.circular(6))))))])),const SizedBox(height:8),Text(summary)]) );}}
class SimpleLineChart extends StatelessWidget { const SimpleLineChart({required this.values,required this.summary,super.key});final List<double> values;final String summary;@override Widget build(BuildContext context)=>Semantics(label:summary,child:CustomPaint(size:const Size(double.infinity,120),painter:_LinePainter(values,Theme.of(context).colorScheme.primary),child:Align(alignment:Alignment.bottomLeft,child:Text(summary))));}
class _LinePainter extends CustomPainter { _LinePainter(this.values,this.color);final List<double> values;final Color color;@override void paint(Canvas c,Size s){if(values.length<2)return;final max=values.fold<double>(1,(a,b)=>math.max(a,b)),p=Paint()..color=color..strokeWidth=3..style=PaintingStyle.stroke;final path=Path();for(var i=0;i<values.length;i++){final x=s.width*i/(values.length-1),y=(s.height-24)*(1-values[i]/max);if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p);}@override bool shouldRepaint(covariant _LinePainter old)=>old.values!=values||old.color!=color;}
class DonutChart extends StatelessWidget { const DonutChart({required this.progress,required this.label,super.key});final double progress;final String label;@override Widget build(BuildContext context)=>Semantics(label:'$label ${(progress*100).round()} percent',child:SizedBox.square(dimension:120,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:progress,strokeWidth:14),Text('${(progress*100).round()}%\n$label',textAlign:TextAlign.center)])));}
class FunnelChart extends StatelessWidget { const FunnelChart({required this.report,super.key});final FunnelReport report;@override Widget build(BuildContext context){final first=report.stages.first.count;return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(report.name,style:Theme.of(context).textTheme.titleLarge),for(var i=0;i<report.stages.length;i++) Padding(padding:const EdgeInsets.symmetric(vertical:4),child:FractionallySizedBox(widthFactor:math.max(.18,report.stages[i].count/first),child:Container(padding:const EdgeInsets.all(10),color:Theme.of(context).colorScheme.secondaryContainer,child:Text('${report.stages[i].name}: ${report.stages[i].count} · ${report.stages[i].conversionFrom(first).toStringAsFixed(1)}%'))))]);}}
class AnalyticsStateView<T> extends StatelessWidget { const AnalyticsStateView({required this.value,required this.builder,super.key});final AsyncSnapshot<T> value;final Widget Function(T) builder;@override Widget build(BuildContext context){if(value.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(value.hasError)return Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off,size:48),const Text('Data temporarily unavailable'),TextButton(onPressed:(){},child:const Text('Retry'))]));return builder(value.data as T);}}
