import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../generated/l10n/app_localizations.dart';
import '../application/analytics_providers.dart';
import '../domain/analytics_models.dart';
import 'analytics_widgets.dart';

String _rangeLabel(AppLocalizations l,AnalyticsTimeRange range)=>switch(range){AnalyticsTimeRange.today=>l.analyticsToday,AnalyticsTimeRange.last7Days=>l.analytics7Days,AnalyticsTimeRange.last30Days=>l.analytics30Days,AnalyticsTimeRange.last90Days=>l.analytics90Days,AnalyticsTimeRange.custom=>l.analyticsCustom};
class _RangePicker extends ConsumerWidget { const _RangePicker({this.custom=true});final bool custom;@override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!,value=ref.watch(analyticsRangeProvider);return DropdownButton<AnalyticsTimeRange>(value:value==AnalyticsTimeRange.custom&&!custom?AnalyticsTimeRange.last30Days:value,items:[for(final r in AnalyticsTimeRange.values)if(custom||r!=AnalyticsTimeRange.custom)DropdownMenuItem(value:r,child:Text(_rangeLabel(l,r)))],onChanged:(v)=>ref.read(analyticsRangeProvider.notifier).state=v!);}}
Widget _async<T>(AsyncValue<T> value,Widget Function(T) data)=>value.when(data:data,loading:()=>const Center(child:CircularProgressIndicator()),error:(_,__)=>const _EmptyState(icon:Icons.cloud_off,title:'Data temporarily unavailable'));
class _EmptyState extends StatelessWidget { const _EmptyState({required this.icon,required this.title});final IconData icon;final String title;@override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:52),const SizedBox(height:12),Text(title),TextButton(onPressed:(){},child:const Text('Retry'))])));}

class BuyerInsightsScreen extends ConsumerWidget { const BuyerInsightsScreen({super.key});@override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!;return Scaffold(appBar:AppBar(title:Text(l.buyerInsights),actions:const [_RangePicker(custom:false)]),body:_async(ref.watch(buyerInsightsProvider),(items)=>items.isEmpty?const _EmptyState(icon:Icons.insights,title:'No analytics data'):ListView(padding:const EdgeInsets.all(16),children:[Text(l.privacySafeDemo,style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:12),SimpleBarChart(values:const [4,7,5,9,8,12,10],summary:l.activitySummary),const SizedBox(height:16),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:380,mainAxisExtent:120,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:items.length,itemBuilder:(_,i)=>Card(child:ListTile(title:Text(items[i].title),subtitle:Text(items[i].summary),trailing:Text(items[i].value,style:Theme.of(context).textTheme.titleLarge))))])));}}

class SellerAnalyticsScreen extends ConsumerWidget { const SellerAnalyticsScreen({super.key});@override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!;return Scaffold(appBar:AppBar(title:Text(l.sellerAnalytics),actions:const [_RangePicker()]),body:_async(ref.watch(sellerMetricsProvider),(metrics)=>ListView(padding:const EdgeInsets.all(16),children:[Text(l.aggregatedDemoData),const SizedBox(height:12),SimpleLineChart(values:const [34,49,42,68,61,84,92],summary:l.engagementTrendSummary),const SizedBox(height:18),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:280,mainAxisExtent:135,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:metrics.length,itemBuilder:(_,i)=>MetricTrendCard(metric:metrics[i].metric))])));}}

enum ProductSort { mostViewed,mostSearched,mostWatchlisted,highestDemand,lowestPerformance,stalePrice,outOfStock }
class ProductPerformanceScreen extends ConsumerStatefulWidget { const ProductPerformanceScreen({super.key});@override ConsumerState<ProductPerformanceScreen> createState()=>_ProductPerformanceScreenState();}
class _ProductPerformanceScreenState extends ConsumerState<ProductPerformanceScreen>{ProductSort sort=ProductSort.mostViewed;@override Widget build(BuildContext context){final l=AppLocalizations.of(context)!;return Scaffold(appBar:AppBar(title:Text(l.productPerformance)),body:_async(ref.watch(productPerformanceProvider),(raw){final items=[...raw];switch(sort){case ProductSort.mostViewed:items.sort((a,b)=>b.views.compareTo(a.views));break;case ProductSort.mostSearched:items.sort((a,b)=>b.searchAppearances.compareTo(a.searchAppearances));break;case ProductSort.mostWatchlisted:items.sort((a,b)=>b.watchlistAdds.compareTo(a.watchlistAdds));break;case ProductSort.highestDemand:items.sort((a,b)=>a.demand.index.compareTo(b.demand.index));break;case ProductSort.lowestPerformance:items.sort((a,b)=>a.performanceScore.compareTo(b.performanceScore));break;case ProductSort.stalePrice:items.sort((a,b)=>a.updatedAt.compareTo(b.updatedAt));break;case ProductSort.outOfStock:items.sort((a,b)=>a.inStock?1:-1);break;}return ListView(padding:const EdgeInsets.all(16),children:[DropdownButtonFormField(value:sort,decoration:InputDecoration(labelText:l.sortBy,border:const OutlineInputBorder()),items:[for(final v in ProductSort.values)DropdownMenuItem(value:v,child:Text(v.name))],onChanged:(v)=>setState(()=>sort=v!)),const SizedBox(height:12),if(items.isEmpty)_EmptyState(icon:Icons.inventory_2_outlined,title:l.noProductPerformance),for(final p in items)Card(child:ExpansionTile(title:Text(p.name),subtitle:Text('${NumberFormat.currency(locale:'en_IN',symbol:'₹',decimalDigits:0).format(p.price)} · ${p.inStock?l.inStock:l.outOfStock} · ${p.pricePosition}'),trailing:Chip(label:Text(p.demand.name)),children:[Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:18,runSpacing:10,children:[Text('Views ${p.views}'),Text('Search ${p.searchAppearances}'),Text('Comparisons ${p.comparisonViews}'),Text('Watchlists ${p.watchlistAdds}'),Text('Requests ${p.requests}'),Text('Offer clicks ${p.offerClicks}'),Text('Conversion ${p.conversionProxy.toStringAsFixed(1)}%'),Text('Updated ${DateFormat.yMMMd().format(p.updatedAt)}')]))]))]);}));}}

class SellerMarketAnalyticsScreen extends ConsumerWidget { const SellerMarketAnalyticsScreen({super.key});@override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!;return DefaultTabController(length:4,child:Scaffold(appBar:AppBar(title:Text(l.marketAnalytics),bottom:TabBar(isScrollable:true,tabs:[Tab(text:l.priceCompetitiveness),Tab(text:l.demandAnalytics),Tab(text:l.areaAnalytics),Tab(text:l.campaignAnalytics)])),body:TabBarView(children:[_Prices(),_Demand(),_Areas(),_Campaigns()])));}}
class _Prices extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(priceCompetitivenessProvider),(items)=>ListView(padding:const EdgeInsets.all(12),children:[for(final p in items)Card(child:ListTile(title:Text(p.product),subtitle:Text('Seller ₹${p.sellerPrice.toStringAsFixed(0)} · nearby ₹${p.lowest.toStringAsFixed(0)}–₹${p.highest.toStringAsFixed(0)} · average ₹${p.average.toStringAsFixed(0)}\n${p.suggestion}'),trailing:Chip(label:Text(p.label.name))))]));}
class _Demand extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(demandAnalyticsProvider),(items)=>ListView(padding:const EdgeInsets.all(12),children:[const SimpleLineChart(values:[42,56,51,78,92,88,110],summary:'Aggregated demand increased over the selected period.'),for(final d in items)Card(child:ListTile(title:Text(d.product),subtitle:Text('Searches ${d.searches} · Watchlists ${d.watchlists} · Requests ${d.requests}\nBuyer intent ${d.buyerIntents} · Supply ${d.supply} · Ratio ${d.ratio.toStringAsFixed(1)}'),trailing:Chip(label:Text(d.level.name))))]));}
class _Areas extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(areaAnalyticsProvider),(items)=>ListView(padding:const EdgeInsets.all(12),children:[Wrap(spacing:8,runSpacing:8,children:[for(final a in items)Container(width:150,height:100,color:Theme.of(c).colorScheme.primaryContainer.withAlpha((255*a.demand/100).round()),padding:const EdgeInsets.all(12),child:Text('${a.area}\nDemand ${a.demand}\n${a.popularCategory}'))]),for(final a in items)Card(child:ListTile(title:Text(a.area),subtitle:Text('${a.activeSellers} sellers · ${a.availability}% availability · ₹${a.averagePrice.toStringAsFixed(0)} average\n${a.requests} requests · ${a.supplyGaps} supply gaps')))]));}
class _Campaigns extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(campaignAnalyticsProvider),(items)=>ListView(padding:const EdgeInsets.all(12),children:[for(final x in items)Card(child:ListTile(title:Text(x.name),subtitle:Text('${x.status} · ${DateFormat.yMMMd().format(x.start)} – ${DateFormat.yMMMd().format(x.end)}\n${x.impressions} impressions · ${x.views} views · ${x.clicks} clicks · ${x.followers} follows · ${x.requests} requests\nCTR ${x.clickThroughRate.toStringAsFixed(1)}% · Engagement ${x.engagementRate.toStringAsFixed(1)}%')))]));}

class AdminBusinessIntelligenceScreen extends ConsumerWidget { const AdminBusinessIntelligenceScreen({super.key});@override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!;return DefaultTabController(length:5,child:Scaffold(appBar:AppBar(title:Text(l.businessIntelligence),bottom:TabBar(isScrollable:true,tabs:[Tab(text:l.overview),Tab(text:l.funnels),Tab(text:l.retention),Tab(text:l.searchIntelligence),Tab(text:l.dataQuality)])),body:TabBarView(children:[_Platform(),_Funnels(),_Retention(),_SearchIntel(),_DataQuality()])));}}
class _Platform extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(platformMetricsProvider),(items)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('DEMO PLATFORM AND FINANCIAL DATA'),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:260,mainAxisExtent:135,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:items.length,itemBuilder:(_,i)=>MetricTrendCard(metric:items[i]))]));}
class _Funnels extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(funnelsProvider),(items)=>ListView(padding:const EdgeInsets.all(16),children:[for(final f in items)Card(child:Padding(padding:const EdgeInsets.all(16),child:FunnelChart(report:f))) ]));}
class _Retention extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(retentionProvider),(items)=>ListView(padding:const EdgeInsets.all(16),children:[for(final x in items)Card(child:ListTile(title:Text(x.name),subtitle:Text(x.summary),trailing:Text(x.value.toStringAsFixed(0)))),const Card(child:Padding(padding:EdgeInsets.all(20),child:Text('Cohort table placeholder · no user tracking identifiers')))]));}
class _SearchIntel extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(searchIntelligenceProvider),(items)=>ListView(padding:const EdgeInsets.all(16),children:[for(final x in items)Card(child:ListTile(title:Text(x.term),subtitle:Text('${x.category} · ${x.count} searches'),trailing:PopupMenuButton<SearchIntelligenceAction>(onSelected:(a)async{await r.read(searchIntelligenceRepositoryProvider).apply(x,a);},itemBuilder:(_)=>[for(final a in SearchIntelligenceAction.values)PopupMenuItem(value:a,child:Text(a.name))]))) ]));}
class _DataQuality extends ConsumerWidget{@override Widget build(c,r)=>_async(r.watch(dataQualityProvider),(items)=>ListView(padding:const EdgeInsets.all(16),children:[for(final x in items)Card(child:ListTile(leading:CircleAvatar(child:Text('${x.count}')),title:Text(x.title),subtitle:Text('${x.severity} · ${x.recordType}'),trailing:TextButton(onPressed:(){},child:const Text('Open record'))))]));}

class ReportBuilderScreen extends ConsumerStatefulWidget { const ReportBuilderScreen({super.key});@override ConsumerState<ReportBuilderScreen> createState()=>_ReportBuilderScreenState();}
class _ReportBuilderScreenState extends ConsumerState<ReportBuilderScreen>{String metric='Search volume';List<Map<String,Object>>? result;@override Widget build(c){final l=AppLocalizations.of(c)!;return Scaffold(appBar:AppBar(title:Text(l.reportBuilder)),body:ListView(padding:const EdgeInsets.all(16),children:[DropdownButtonFormField(value:metric,decoration:const InputDecoration(labelText:'Metric'),items:[for(final x in ['Search volume','Product views','Demand','Subscriptions'])DropdownMenuItem(value:x,child:Text(x))],onChanged:(v)=>setState(()=>metric=v!)),const SizedBox(height:12),const Wrap(spacing:8,children:[Chip(label:Text('Category: All')),Chip(label:Text('Radius: 5 km')),Chip(label:Text('Plan: All')),Chip(label:Text('Verification: All')),Chip(label:Text('Demand: All'))]),FilledButton(onPressed:()async{final value=await ref.read(reportRepositoryProvider).generate(ReportDefinition(metric,AnalyticsTimeRange.last30Days,const []));setState(()=>result=value);},child:const Text('Generate demo report')),if(result!=null)...[DataTable(columns:const [DataColumn(label:Text('Period')),DataColumn(label:Text('Value')),DataColumn(label:Text('Status'))],rows:[for(final row in result!)DataRow(cells:[DataCell(Text('${row['period']}')),DataCell(Text('${row['value']}')),DataCell(Text('${row['status']}'))])]),Wrap(children:[TextButton.icon(onPressed:(){},icon:const Icon(Icons.table_view),label:const Text('CSV export placeholder')),TextButton.icon(onPressed:(){},icon:const Icon(Icons.picture_as_pdf),label:const Text('PDF export placeholder'))])]]));}}

class AnalyticsPrivacyScreen extends ConsumerWidget { const AnalyticsPrivacyScreen({super.key,this.seller=false});final bool seller;@override Widget build(BuildContext c,WidgetRef r){final l=AppLocalizations.of(c)!,s=r.watch(analyticsPrivacyProvider),n=r.read(analyticsPrivacyProvider.notifier);return Scaffold(appBar:AppBar(title:Text(l.analyticsPrivacy)),body:ListView(padding:const EdgeInsets.all(16),children:[Text(l.analyticsPrivacyExplanation),if(!seller)...[SwitchListTile(title:Text(l.basicUsageAnalytics),subtitle:Text(l.basicUsageExplanation),value:s.basicUsage,onChanged:n.setBasic),SwitchListTile(title:Text(l.recommendationAnalytics),value:s.recommendations,onChanged:n.setRecommendations)]else...[SwitchListTile(title:Text(l.businessPerformanceAnalytics),value:s.businessPerformance,onChanged:n.setBusiness),SwitchListTile(title:Text(l.marketComparisonAnalytics),value:s.marketComparisons,onChanged:n.setMarket)],ListTile(title:Text(l.collectedCategories),subtitle:const Text('Screens · searches · products · offers · watchlist · subscriptions')),OutlinedButton.icon(onPressed:(){n.clear();ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(l.localAnalyticsCleared)));},icon:const Icon(Icons.delete_outline),label:Text(l.clearLocalAnalytics))]));}}
