import 'dart:async';
import 'security_models.dart';

abstract interface class PermissionService { bool hasPermission(SecurityRole role, Permission permission); }
class LocalPermissionService implements PermissionService {
  static final _map=<SecurityRole,Set<Permission>>{SecurityRole.superAdmin:Set.from(Permission.values),SecurityRole.admin:{Permission.viewAuditLog,Permission.viewAggregatedAnalytics,Permission.manageSubscriptions},SecurityRole.supportAdmin:{Permission.resolveSupportCases},SecurityRole.catalogAdmin:{Permission.editCatalog},SecurityRole.moderationAdmin:{Permission.suspendSeller,Permission.viewAuditLog},SecurityRole.sellerVerificationAdmin:{Permission.approveSeller}};
  @override bool hasPermission(SecurityRole role,Permission permission)=>_map[role]?.contains(permission)??false;
}
abstract interface class ConsentService { List<ConsentRecord> get history; ConsentRecord record({required ConsentType type,required String version,required bool accepted,required String sourceScreen,required bool required}); ConsentRecord withdraw(ConsentType type); bool permits(ConsentType type,String version); }
class LocalConsentService implements ConsentService { final List<ConsentRecord> _records=[]; @override List<ConsentRecord> get history=>List.unmodifiable(_records); @override ConsentRecord record({required ConsentType type,required String version,required bool accepted,required String sourceScreen,required bool required}) { final value=ConsentRecord(type:type,version:version,status:accepted?ConsentStatus.accepted:ConsentStatus.rejected,timestamp:DateTime.now().toUtc(),sourceScreen:sourceScreen,required:required);_records.add(value);return value;} @override ConsentRecord withdraw(ConsentType type){final prior=_records.lastWhere((e)=>e.type==type);if(prior.required)throw StateError('Required consent cannot be withdrawn while the related flow is active.');final now=DateTime.now().toUtc();final value=ConsentRecord(type:type,version:prior.version,status:ConsentStatus.withdrawn,timestamp:prior.timestamp,sourceScreen:prior.sourceScreen,required:false,withdrawalTimestamp:now);_records.add(value);return value;} @override bool permits(ConsentType type,String version){final values=_records.where((e)=>e.type==type&&e.version==version);return values.isNotEmpty&&values.last.status==ConsentStatus.accepted;} }
abstract interface class LegalDocumentRepository { Future<List<LegalDocument>> all(); }
abstract interface class AccountDataRepository { Future<void> clearSearchHistory(); Future<void> clearLocationHistory(); Future<void> clearAnalyticsHistory(); Future<void> clearWatchlist(); }
abstract interface class AccountDeletionService { AccountDeletionRequest get state; void requestConfirmation(); void confirmReauthentication(); void request(); void cancel(); }
class LocalAccountDeletionService implements AccountDeletionService { LocalAccountDeletionService(this.userId):_state=AccountDeletionRequest(userId:userId,status:AccountDeletionStatus.notRequested,updatedAt:DateTime.now().toUtc());final String userId;AccountDeletionRequest _state;@override AccountDeletionRequest get state=>_state;void _set(AccountDeletionStatus s)=>_state=_state.withStatus(s,DateTime.now().toUtc());@override void requestConfirmation()=>_set(AccountDeletionStatus.confirmationRequired);@override void confirmReauthentication(){if(_state.status!=AccountDeletionStatus.confirmationRequired)throw StateError('Confirmation required');_set(AccountDeletionStatus.reauthenticationRequired);}@override void request(){if(_state.status!=AccountDeletionStatus.reauthenticationRequired)throw StateError('Re-authentication required');_set(AccountDeletionStatus.requested);}@override void cancel(){if(!{AccountDeletionStatus.requested,AccountDeletionStatus.gracePeriod}.contains(_state.status))throw StateError('Deletion cannot be cancelled');_set(AccountDeletionStatus.cancelled);} }
enum SecureStorageKey { sessionToken, refreshToken, userId, consentRecord, deviceSession, securityPreferences }
abstract interface class SecureStorage { Future<void> write(SecureStorageKey key,String value); Future<String?> read(SecureStorageKey key); Future<void> delete(SecureStorageKey key); Future<void> clear(); }
class MemorySecureStorage implements SecureStorage { final _values=<SecureStorageKey,String>{};@override Future<void> write(SecureStorageKey k,String v)async=>_values[k]=v;@override Future<String?> read(SecureStorageKey k)async=>_values[k];@override Future<void> delete(SecureStorageKey k)async=>_values.remove(k);@override Future<void> clear()async=>_values.clear(); }
enum LogLevel { debug,info,warning,error,critical }
abstract interface class RedactingLogger { void log(LogLevel level,String message,{Map<String,Object?> context}); }
class LocalRedactingLogger implements RedactingLogger { LocalRedactingLogger({this.mode=BuildMode.development,this.sink});final BuildMode mode;final void Function(String)? sink;static String redact(String input)=>input.replaceAll(RegExp(r'(?<!\d)\d{10}(?!\d)'),'[REDACTED_PHONE]').replaceAll(RegExp(r'(otp|token|password|authorization|payment|adminNote)\s*[:=]\s*[^\s,]+',caseSensitive:false),'[REDACTED]');@override void log(LogLevel level,String message,{Map<String,Object?> context=const {}}){if(mode==BuildMode.release&&level==LogLevel.debug)return;sink?.call('${level.name}: ${redact(message)} ${redact(context.toString())}');} }
abstract interface class RateLimitService { RateLimitState record(String subject,RateLimitRule rule); void reset(String subject); }
class LocalRateLimitService implements RateLimitService {final _counts=<String,int>{};@override RateLimitState record(String s,RateLimitRule r){final n=_counts.update('${r.key}:$s',(v)=>v+1,ifAbsent:()=>1);if(n>=r.blockAt)return RateLimitState.blocked;if(n>r.limit)return RateLimitState.temporarilyLimited;if(n>=r.warningAt)return RateLimitState.warning;return RateLimitState.allowed;}@override void reset(String s)=>_counts.removeWhere((k,v)=>k.endsWith(':$s'));}
abstract interface class AbuseReportRepository { Future<void> submit(AbuseReport report); Future<List<AbuseReport>> all(); }
class LocalAbuseReportRepository implements AbuseReportRepository {final _items=<AbuseReport>[];@override Future<void> submit(AbuseReport r)async=>_items.add(r);@override Future<List<AbuseReport>> all()async=>List.unmodifiable(_items);}
abstract interface class BlockedSellerRepository { Future<void> block(String sellerId);Future<void> unblock(String sellerId);bool isBlocked(String sellerId);List<T> excludeBlocked<T>(Iterable<T> items,String Function(T) sellerId); }
class LocalBlockedSellerRepository implements BlockedSellerRepository {final _ids=<String>{};@override Future<void> block(String id)async=>_ids.add(id);@override Future<void> unblock(String id)async=>_ids.remove(id);@override bool isBlocked(String id)=>_ids.contains(id);@override List<T> excludeBlocked<T>(Iterable<T> items,String Function(T) id)=>items.where((e)=>!isBlocked(id(e))).toList(growable:false);}
abstract interface class FileValidationService { FileValidationResult validate(SecureFileReference file); }
class LocalFileValidationService implements FileValidationService { static const allowed={'image/jpeg','image/png','application/pdf'};@override FileValidationResult validate(SecureFileReference f){final errors=<String>[];if(f.filename.contains('..')||f.filename.contains('/')||f.filename.contains('\\')||!RegExp(r'^[\w .-]+$').hasMatch(f.filename))errors.add('unsafeFilename');if(f.sizeBytes<=0||f.sizeBytes>10*1024*1024)errors.add('invalidFileSize');if(!allowed.contains(f.mimeType))errors.add('unsupportedMimeType');if(f.category!=FileCategory.sellerVerificationDocument&&f.mimeType=='application/pdf')errors.add('unsupportedCategoryType');return FileValidationResult(errors.isEmpty,errors);} }
enum SessionDecision { allowed,inactivityExpired,absoluteExpired,locked,reauthenticationRequired }
abstract interface class SessionSecurityService { SessionDecision evaluate({required DateTime createdAt,required DateTime lastActivity,required DateTime now,required bool suspended,required bool deleted,required bool sensitiveAction,required DateTime? reauthenticatedAt}); }
class LocalSessionSecurityService implements SessionSecurityService { const LocalSessionSecurityService({this.inactivityTimeout=const Duration(minutes:15),this.absoluteTimeout=const Duration(hours:12),this.reauthenticationWindow=const Duration(minutes:5)});final Duration inactivityTimeout,absoluteTimeout,reauthenticationWindow;@override SessionDecision evaluate({required DateTime createdAt,required DateTime lastActivity,required DateTime now,required bool suspended,required bool deleted,required bool sensitiveAction,required DateTime? reauthenticatedAt}){if(suspended||deleted)return SessionDecision.locked;if(now.difference(createdAt)>=absoluteTimeout)return SessionDecision.absoluteExpired;if(now.difference(lastActivity)>=inactivityTimeout)return SessionDecision.inactivityExpired;if(sensitiveAction&&(reauthenticatedAt==null||now.difference(reauthenticatedAt)>=reauthenticationWindow))return SessionDecision.reauthenticationRequired;return SessionDecision.allowed;} }
abstract interface class SecurityEventRepository { Future<void> append(SecurityEvent event);Future<List<SecurityEvent>> all(); }
abstract interface class FeatureFlagService { BuildMode get mode;bool enabled(FeatureFlag flag); }
class LocalFeatureFlagService implements FeatureFlagService {const LocalFeatureFlagService(this.mode);@override final BuildMode mode;@override bool enabled(FeatureFlag flag)=>mode!=BuildMode.release;}
abstract interface class ReleaseReadinessService { List<ReleaseChecklistItem> get items;bool get ready; }
class LocalReleaseReadinessService implements ReleaseReadinessService {LocalReleaseReadinessService(this.items);@override final List<ReleaseChecklistItem> items;@override bool get ready=>items.where((e)=>e.productionBlocker).every((e)=>e.complete);}
class AppendOnlyAuditLog {final _items=<AuditRecord>[];List<AuditRecord> get records=>List.unmodifiable(_items);void append(AuditRecord record){if(record.reason.trim().isEmpty)throw ArgumentError('A reason is required');_items.add(record);} }
class SafeError {const SafeError(this.message,this.correlationId);final String message,correlationId;factory SafeError.from(Object error,{required String correlationId,BuildMode mode=BuildMode.release})=>SafeError(mode==BuildMode.development?'Something went wrong (${error.runtimeType}).':'Something went wrong. Contact support if it continues.',correlationId);}
abstract final class SensitiveValueMasker {static MaskedValue mobile(String v)=>MaskedValue(v.length<4?'****':'******${v.substring(v.length-4)}');static MaskedValue email(String v){final p=v.split('@');return MaskedValue(p.length!=2?'***':'${p[0].isEmpty?'*':p[0][0]}***@${p[1]}');}static MaskedValue reference(String v)=>MaskedValue(v.length<=4?'****':'***${v.substring(v.length-4)}');static String safeText(String value,{int maxLength=500}){final clean=value.replaceAll(RegExp(r'[<>]'),'').trim();return clean.substring(0,clean.length.clamp(0,maxLength));}}
class InputValidator {String? requiredText(String? v,{int max=120}){final s=v?.trim()??'';if(s.isEmpty)return 'required';if(s.length>max)return 'tooLong';return null;}String? mobile(String? v)=>RegExp(r'^\+?[1-9]\d{7,14}$').hasMatch(v?.trim()??'')?null:'invalidMobile';String? email(String? v)=>RegExp(r'^[^\s@]+@[^\s@]+\.[^\s@]+$').hasMatch(v?.trim()??'')?null:'invalidEmail';String? coordinate(num? v,{required bool latitude})=>v==null||v<(latitude?-90:-180)||v>(latitude?90:180)?'invalidCoordinate':null;String? price(num? v)=>v==null||v<0?'invalidPrice':null;String? quantity(num? v)=>v==null||v<=0||v%1!=0?'invalidQuantity':null;String? offer(num? offer,num? selling)=>offer==null||selling==null||offer<0||offer>selling?'invalidOfferPrice':null;String? filename(String? v)=>v==null||v.contains('..')||v.contains('/')||v.contains('\\')||!RegExp(r'^[\w .-]+$').hasMatch(v)?'unsafeFilename':null;String? adminReason(String? v)=>requiredText(v,max:500);String? barcode(String? v)=>RegExp(r'^\d{8,14}$').hasMatch(v??'')?null:'invalidBarcode';String? gstin(String? v)=>RegExp(r'^[0-9A-Z]{15}$').hasMatch(v??'')?null:'invalidGstin';String? radius(num? v)=>v==null||v<=0||v>100?'invalidRadius':null;String? mime(String? v)=>LocalFileValidationService.allowed.contains(v)?null:'unsupportedMimeType';}
