import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../application/location_controller.dart';
import '../domain/geo_models.dart';
class LocationSetupScreen extends ConsumerWidget { const LocationSetupScreen({super.key});
 @override Widget build(BuildContext context,WidgetRef ref){final s=ref.watch(locationControllerProvider), c=ref.read(locationControllerProvider.notifier);return Scaffold(appBar:AppBar(title:const Text('Set your location')),body:ListView(padding:const EdgeInsets.all(20),children:[Icon(Icons.location_on_outlined,size:72,color:Theme.of(context).colorScheme.primary),Text('Find nearby shops, prices and watchlist matches',textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),const Text('ASKODOX uses your location only to show relevant nearby results. Your home address is never shared with sellers.',textAlign:TextAlign.center),const SizedBox(height:20),Card(child:ListTile(leading:const Icon(Icons.privacy_tip_outlined),title:Text(_permission(s.permission)),subtitle:const Text('You stay in control and can use a manual location instead.'))),FilledButton.icon(onPressed:()=>c.requestPermission(),icon:const Icon(Icons.my_location),label:const Text('Request location permission')),if(s.permission==LocationPermissionStatus.deniedPermanently||s.permission==LocationPermissionStatus.servicesDisabled) OutlinedButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Device settings will open here in a future release.'))),child:const Text('Open settings')),if(s.permission!=LocationPermissionStatus.notRequested) OutlinedButton(onPressed:c.retryLocation,child:const Text('Retry location')),const Divider(height:32),Text('Choose manually',style:Theme.of(context).textTheme.titleLarge),..._suggestions.map((l)=>ListTile(leading:const Icon(Icons.place_outlined),title:Text(l.name),subtitle:Text(l.address),onTap:()async{await c.selectManualLocation(l);if(context.mounted)context.go('/nearby');})),TextButton(onPressed:()=>_coordinates(context,c),child:const Text('Enter latitude and longitude for testing')),FilledButton.tonal(onPressed:()=>context.go('/nearby'),child:const Text('Continue with manual location'))])); }
 static String _permission(LocationPermissionStatus p)=>switch(p){LocationPermissionStatus.notRequested=>'Location permission not requested',LocationPermissionStatus.granted=>'Location permission granted',LocationPermissionStatus.denied=>'Location permission denied',LocationPermissionStatus.deniedPermanently=>'Location permission denied permanently',LocationPermissionStatus.servicesDisabled=>'Location services disabled'};
 Future<void> _coordinates(BuildContext context,LocationController c)async{final lat=TextEditingController(text:'17.4156'),lng=TextEditingController(text:'78.4347');await showDialog(context:context,builder:(ctx)=>AlertDialog(title:const Text('Manual coordinates'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(key:const Key('latitudeField'),controller:lat,decoration:const InputDecoration(labelText:'Latitude')),TextField(key:const Key('longitudeField'),controller:lng,decoration:const InputDecoration(labelText:'Longitude'))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:(){final p=GeoPoint(double.tryParse(lat.text)??double.nan,double.tryParse(lng.text)??double.nan);c.selectManualLocation(BuyerSavedLocation(id:'manual',name:'Manual location',address:'Custom coordinates',point:p,type:SavedLocationType.custom));Navigator.pop(ctx);},child:const Text('Use location'))]));}
}
const _suggestions=[BuyerSavedLocation(id:'banjara',name:'Banjara Hills',address:'Hyderabad, Telangana',point:GeoPoint(17.4156,78.4347),type:SavedLocationType.currentLocation),BuyerSavedLocation(id:'jubilee',name:'Home',address:'Jubilee Hills, Hyderabad',point:GeoPoint(17.4326,78.4071),type:SavedLocationType.home),BuyerSavedLocation(id:'work',name:'Work',address:'Somajiguda, Hyderabad',point:GeoPoint(17.4239,78.4738),type:SavedLocationType.work)];
