import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../application/location_controller.dart';
import '../domain/geo_models.dart';
class NearbyShopsScreen extends ConsumerWidget { const NearbyShopsScreen({super.key});
 @override Widget build(BuildContext context,WidgetRef ref){final s=ref.watch(locationControllerProvider),c=ref.read(locationControllerProvider.notifier);return Scaffold(appBar:AppBar(title:const Text('Nearby shops'),actions:[IconButton(tooltip:'Location settings',onPressed:()=>context.push('/location'),icon:const Icon(Icons.location_on_outlined)),IconButton(tooltip:'Filters',onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Nearby filters placeholder'))),icon:const Icon(Icons.filter_list))]),body:Column(children:[Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:Row(children:[Expanded(child:Text('${_radius(s.radiusMetres)} radius · ${s.shops.length} results',style:const TextStyle(fontWeight:FontWeight.bold))),SegmentedButton<MapDisplayMode>(key:const Key('viewToggle'),segments:const [ButtonSegment(value:MapDisplayMode.map,icon:Icon(Icons.map_outlined),label:Text('Map')),ButtonSegment(value:MapDisplayMode.list,icon:Icon(Icons.list),label:Text('List'))],selected:{s.mode},onSelectionChanged:(v)=>c.toggleMode(v.first))])),SizedBox(height:46,child:ListView(padding:const EdgeInsets.symmetric(horizontal:12),scrollDirection:Axis.horizontal,children:[for(final r in const [100.0,200,500,1000,2000,5000,10000,25000,50000,7500]) Padding(padding:const EdgeInsets.only(right:6),child:ChoiceChip(label:Text(r==7500?'Custom (${_radius(r)})':_radius(r)),selected:s.radiusMetres==r,onSelected:(_)=>c.setRadius(r))) ])),const SizedBox(height:8),Expanded(child:s.loading?const Center(child:CircularProgressIndicator()):s.mode==MapDisplayMode.map?_MockMap(state:s):_ShopList(shops:s.shops)),if(s.message!=null) Material(color:Theme.of(context).colorScheme.secondaryContainer,child:ListTile(dense:true,title:Text(s.message!),trailing:TextButton(onPressed:c.refresh,child:const Text('Retry'))))]));}
 static String _radius(double m)=>m<1000?'${m.round()} m':'${(m/1000).toStringAsFixed(m%1000==0?0:1)} km';
}
class _MockMap extends ConsumerWidget {const _MockMap({required this.state});final LocationState state;@override Widget build(BuildContext context,WidgetRef ref){final c=ref.read(locationControllerProvider.notifier);final selected=state.shops.where((x)=>x.id==state.selectedShopId).firstOrNull;return Stack(children:[Semantics(label:'Mock map canvas',child:Container(key:const Key('mockMap'),margin:const EdgeInsets.all(12),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(24)),child:CustomPaint(painter:_MapPainter(Theme.of(context).colorScheme),child:Stack(children:[Positioned(left:MediaQuery.sizeOf(context).width*.42,top:130,child:const _Marker(icon:Icons.person_pin_circle,label:'You')),for(var i=0;i<state.shops.length;i++)Positioned(left:40.0+(i*95)%260,top:220.0+(i%2)*90,child:GestureDetector(onTap:()=>c.selectShop(state.shops[i].id),child:_Marker(icon:Icons.store,label:state.shops[i].name))) ]))),Positioned(right:24,top:24,child:FloatingActionButton.small(heroTag:'recenter',tooltip:'Recenter',onPressed:()=>c.moveMap(state.defaultLocation?.point??const GeoPoint(17.4156,78.4347)),child:const Icon(Icons.my_location))),Positioned(left:24,right:24,top:24,child:Center(child:FilledButton.icon(key:const Key('searchArea'),onPressed:c.searchThisArea,icon:const Icon(Icons.refresh),label:const Text('Search this area')))),Positioned(left:24,bottom:selected==null?24:150,child:OutlinedButton.icon(onPressed:c.saveSelectedArea,icon:const Icon(Icons.bookmark_add_outlined),label:const Text('Save this area'))),if(selected!=null)Positioned(left:16,right:16,bottom:12,child:_ShopCard(shop:selected))]);}}
class _Marker extends StatelessWidget{const _Marker({required this.icon,required this.label});final IconData icon;final String label;@override Widget build(BuildContext context)=>Tooltip(message:label,child:Icon(icon,size:44,color:Theme.of(context).colorScheme.primary));}
class _MapPainter extends CustomPainter{_MapPainter(this.colors);final ColorScheme colors;@override void paint(Canvas c,Size s){final p=Paint()..color=colors.primary.withOpacity(.12)..style=PaintingStyle.stroke..strokeWidth=3;c.drawCircle(Offset(s.width/2,s.height/2),s.shortestSide*.3,p);final road=Paint()..color=colors.outlineVariant..strokeWidth=4;for(double y=70;y<s.height;y+=100)c.drawLine(Offset(0,y),Offset(s.width,y+35),road);}@override bool shouldRepaint(covariant _MapPainter old)=>false;}
class _ShopList extends StatelessWidget{const _ShopList({required this.shops});final List<NearbyShop> shops;@override Widget build(BuildContext context)=>shops.isEmpty?const _Empty():ListView.builder(padding:const EdgeInsets.all(12),itemCount:shops.length,itemBuilder:(_,i)=>_ShopCard(shop:shops[i]));}
class _ShopCard extends ConsumerWidget{const _ShopCard({required this.shop});final NearbyShop shop;@override Widget build(BuildContext context,WidgetRef ref)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[ListTile(contentPadding:EdgeInsets.zero,leading:const CircleAvatar(child:Icon(Icons.storefront)),title:Text(shop.name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${shop.category} · ${shop.distanceMetres<1000?'${shop.distanceMetres.round()} m':'${(shop.distanceMetres/1000).toStringAsFixed(1)} km'}'),trailing:Chip(avatar:Icon(shop.verified?Icons.verified:Icons.info_outline,size:16),label:Text('${shop.trustScore}'))),Wrap(spacing:6,children:[Chip(label:Text(shop.isOpen?'Open':'Closed')),Chip(label:Text('${shop.productCount} products')),Chip(label:Text('${shop.watchlistMatches} matches')),Chip(label:Text('${shop.activeOffers} offers'))]),Wrap(children:[TextButton(onPressed:()=>context.push('/shop/${shop.id}'),child:const Text('View shop')),TextButton(onPressed:()=>ref.read(locationControllerProvider.notifier).selectShop(shop.id),child:const Text('View on map')),PopupMenuButton(itemBuilder:(_)=>const [PopupMenuItem(child:Text('Call (placeholder)')),PopupMenuItem(child:Text('Navigate (placeholder)')),PopupMenuItem(child:Text('Follow shop')),PopupMenuItem(child:Text('Report shop'))])])])));}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext context)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.store_mall_directory_outlined,size:64),const Text('No nearby shops'),const Text('Try a larger radius or choose another location.'),FilledButton(onPressed:()=>context.push('/location'),child:const Text('Choose location'))]));}
