import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:podx/core/api/api_models.dart';import 'package:podx/core/auth/auth_models.dart';import 'package:podx/core/auth/auth_service.dart';import 'package:podx/core/auth/route_guard.dart';import 'package:podx/core/auth/session_manager.dart';import 'package:podx/core/config/environment.dart';
import 'package:podx/core/data/data_state.dart';import 'package:podx/core/pagination/pagination.dart';import 'package:podx/core/persistence/local_store.dart';import 'package:podx/core/providers/backend_providers.dart';import 'package:podx/core/sync/sync_models.dart';
void main(){
 test('configuration validates remote providers',(){expect(()=>AppConfig.fromEnvironment({'APP_ENV':'staging','BACKEND_PROVIDER':'rest'}),throwsFormatException);expect(AppConfig.development().backendProvider,BackendProvider.mock);});
 test('role guard allows public profile and rejects cross-module guest routes',(){const guard=RouteGuard();const guest=AuthSession.loggedOut;final buyer=AuthSession(user:const AuthUser(id:'b',role:UserRole.buyer),status:AuthStatus.loggedIn);final seller=AuthSession(user:const AuthUser(id:'s',role:UserRole.seller),status:AuthStatus.loggedIn);expect(guard.redirect(guest,'/profile'),isNull);expect(guard.redirect(buyer,'/admin/dashboard'),'/forbidden');expect(guard.redirect(seller,'/admin/super/users'),'/forbidden');expect(guard.redirect(seller,'/seller/dashboard'),isNull);});
 test('suspended and expired sessions have dedicated destinations',(){const guard=RouteGuard();expect(guard.redirect(const AuthSession(status:AuthStatus.suspended),'/'),'/account-status');expect(guard.redirect(const AuthSession(status:AuthStatus.sessionExpired),'/profile'),'/auth/session-expired');});
 test('session restores, expires and logs out',()async{final store=MemoryLocalStore();final manager=SessionManager(store,MockAuthenticationService());final expired=AuthSession(user:const AuthUser(id:'x',role:UserRole.buyer),status:AuthStatus.loggedIn,expiresAt:DateTime.now().subtract(const Duration(seconds:1)));await manager.save(expired);expect((await manager.restore()).status,AuthStatus.sessionExpired);await manager.logout();expect(await store.read<Object>(LocalKeys.session),isNull);});
 test('local persistence round trips supported values',()async{final store=MemoryLocalStore();await store.write(LocalKeys.searchRadius,25);await store.write(LocalKeys.watchlist,['p1']);expect(await store.read<int>(LocalKeys.searchRadius),25);expect(await store.read<List<dynamic>>(LocalKeys.watchlist),['p1']);});
 test('API failures map and localize',(){expect(mapApiError(Exception(),statusCode:403).type,ApiFailureType.permission);expect(const ApiFailure(ApiFailureType.network).localizedMessage('te'),contains('నెట్‌వర్క్'));});
 test('pagination loads more, refreshes and reaches end',()async{final pager=MockPaginator(List.generate(5,(i)=>i),pageSize:2);expect((await pager.loadInitial()).items,[0,1]);expect((await pager.loadMore()).items,[0,1,2,3]);expect((await pager.loadMore()).status,PaginationStatus.endOfList);expect((await pager.refresh()).items,[0,1]);});
 test('sync queue completes pending local changes',()async{final sync=MockSyncService();await sync.enqueue(LocalChange(entityType:'product',entityId:'1',operation:'update',payload:const{},createdAt:DateTime.now()));expect(sync.status.pendingCount,1);await sync.sync();expect(sync.status.pendingCount,0);expect(sync.queue.single.status,SyncItemStatus.synced);});
 test('repository services are switchable with Riverpod overrides',(){final custom=MemoryLocalStore();final container=ProviderContainer(overrides:[localStoreProvider.overrideWithValue(custom)]);addTearDown(container.dispose);expect(container.read(localStoreProvider),same(custom));});
}
