import 'package:flutter_test/flutter_test.dart';
import 'package:podx/core/auth/auth_models.dart';
import 'package:podx/core/auth/route_guard.dart';
import 'package:podx/core/security/security_models.dart';
import 'package:podx/core/security/security_services.dart';

void main() {
  group('permissions and route access', () {
    final permissions=LocalPermissionService();
    test('least privilege admin permissions',(){expect(permissions.hasPermission(SecurityRole.catalogAdmin,Permission.editCatalog),isTrue);expect(permissions.hasPermission(SecurityRole.catalogAdmin,Permission.deleteUserData),isFalse);});
    test('permission-protected deep links are forbidden',(){final session=AuthSession(status:AuthStatus.loggedIn,user:const AuthUser(id:'a',role:UserRole.supportAdmin));expect(RouteGuard(permissions).redirect(session,'/admin/auditLog'),'/forbidden');});
    test('suspended and deleted accounts lock out',(){for(final status in [AuthStatus.suspended,AuthStatus.deleted]){expect(const RouteGuard().redirect(AuthSession(status:status),'/'),'/account-status');}});
  });
  group('session security',(){const service=LocalSessionSecurityService();final now=DateTime.utc(2026,1,1,12);
    test('inactivity and absolute expiry',(){expect(service.evaluate(createdAt:now.subtract(const Duration(hours:1)),lastActivity:now.subtract(const Duration(minutes:15)),now:now,suspended:false,deleted:false,sensitiveAction:false,reauthenticatedAt:null),SessionDecision.inactivityExpired);expect(service.evaluate(createdAt:now.subtract(const Duration(hours:12)),lastActivity:now,now:now,suspended:false,deleted:false,sensitiveAction:false,reauthenticatedAt:null),SessionDecision.absoluteExpired);});
    test('sensitive action requires recent reauthentication',(){expect(service.evaluate(createdAt:now,lastActivity:now,now:now,suspended:false,deleted:false,sensitiveAction:true,reauthenticatedAt:null),SessionDecision.reauthenticationRequired);});
  });
  test('masking and logger redaction protect values',(){expect(SensitiveValueMasker.mobile('9876543210').value,'******3210');expect(SensitiveValueMasker.email('person@example.com').value,'p***@example.com');final output=<String>[];LocalRedactingLogger(sink:output.add).log(LogLevel.info,'otp=123456 token=secret phone 9876543210');expect(output.single,contains('[REDACTED]'));expect(output.single,isNot(contains('123456')));expect(output.single,isNot(contains('9876543210')));});
  group('validation',(){final v=InputValidator();test('input and offer rules',(){expect(v.mobile('+919876543210'),isNull);expect(v.price(-1),'invalidPrice');expect(v.quantity(1.5),'invalidQuantity');expect(v.coordinate(91,latitude:true),'invalidCoordinate');expect(v.offer(101,100),'invalidOfferPrice');expect(v.adminReason(''),'required');expect(v.filename('../secret'),'unsafeFilename');});test('file reference validation',(){final f=SecureFileReference(id:'1',category:FileCategory.productImage,filename:'x.exe',mimeType:'application/octet-stream',sizeBytes:20,accessLevel:FileAccessLevel.public);expect(LocalFileValidationService().validate(f).isValid,isFalse);});});
  test('consent accepts, blocks absent version and withdraws optional',(){final s=LocalConsentService();s.record(type:ConsentType.termsOfService,version:'1',accepted:true,sourceScreen:'register',required:true);expect(s.permits(ConsentType.termsOfService,'1'),isTrue);expect(s.permits(ConsentType.privacyPolicy,'1'),isFalse);s.record(type:ConsentType.analytics,version:'1',accepted:true,sourceScreen:'privacy',required:false);expect(s.withdraw(ConsentType.analytics).status,ConsentStatus.withdrawn);expect(s.permits(ConsentType.analytics,'1'),isFalse);expect(()=>s.withdraw(ConsentType.termsOfService),throwsStateError);});
  test('account deletion enforces confirmation and reauthentication',(){final s=LocalAccountDeletionService('u');s.requestConfirmation();s.confirmReauthentication();s.request();expect(s.state.status,AccountDeletionStatus.requested);s.cancel();expect(s.state.status,AccountDeletionStatus.cancelled);});
  test('blocking removes seller data from all downstream surfaces',()async{final s=LocalBlockedSellerRepository();await s.block('bad');final results=s.excludeBlocked([('bad','private'),('good','aggregate')],(e)=>e.$1);expect(results,[('good','aggregate')]);});
  test('rate limit transitions',(){final s=LocalRateLimitService();const r=RateLimitRule(key:'otp',warningAt:2,limit:3,blockAt:5);expect(s.record('u',r),RateLimitState.allowed);expect(s.record('u',r),RateLimitState.warning);s.record('u',r);expect(s.record('u',r),RateLimitState.temporarilyLimited);expect(s.record('u',r),RateLimitState.blocked);});
  test('abuse submission and append-only audit',()async{final reports=LocalAbuseReportRepository();await reports.submit(AbuseReport(id:'r',type:AbuseReportType.privacyConcern,entityReference:'seller',description:'concern',createdAt:DateTime.utc(2026)));expect(await reports.all(),hasLength(1));final audit=AppendOnlyAuditLog();audit.append(AuditRecord(id:'a',actor:'admin',actorRole:'moderationAdmin',permission:Permission.suspendSeller,action:'suspend',entity:'seller',previousState:'active',newState:'suspended',reason:'Repeated abuse',timestamp:DateTime.utc(2026),environment:'development',correlationId:'c',sessionIdentifier:'***1'));expect(audit.records,hasLength(1));expect(()=>audit.records.add(audit.records.first),throwsUnsupportedError);});
  test('release hides developer tools and safe errors hide details',(){const flags=LocalFeatureFlagService(BuildMode.release);for(final flag in FeatureFlag.values){expect(flags.enabled(flag),isFalse);}final e=SafeError.from(Exception('/secret/path token=x'),correlationId:'support-1');expect(e.message,isNot(contains('secret')));expect(e.correlationId,'support-1');});
}
