import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/demo/demo_accounts.dart';
import '../../../core/demo/demo_state.dart';
import '../../../core/providers/backend_providers.dart';

class DemoCenterScreen extends ConsumerStatefulWidget { const DemoCenterScreen({super.key}); @override ConsumerState<DemoCenterScreen> createState()=>_DemoCenterScreenState(); }
class _DemoCenterScreenState extends ConsumerState<DemoCenterScreen> {
  DemoModule _module=DemoModule.commerce; bool _switching=false;
  String _moduleName(DemoModule m)=>switch(m){DemoModule.commerce=>'Buy & Sell',DemoModule.jobs=>'Jobs',DemoModule.services=>'Services',DemoModule.rides=>'Rides',DemoModule.parcel=>'Parcel Delivery',DemoModule.appointments=>'Appointments',DemoModule.catering=>'Catering',DemoModule.localDiscovery=>'Local Discovery'};
  String _stageName(DemoJourneyStage s)=>switch(s){DemoJourneyStage.open=>'Request Open',DemoJourneyStage.matched=>'Matched',DemoJourneyStage.accepted=>'Accepted / Deal Active',DemoJourneyStage.completed=>'Completed / History'};
  void _reset(){DemoRuntime.state.reset();setState((){});ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Demo data reset to the default seed state.')));}
  void _advance(){DemoRuntime.state.advanceJourney(_module);setState((){});}
  Future<void> _enterAs(DemoAccount a) async {if(_switching)return;setState(()=>_switching=true);await ref.read(authSessionProvider.notifier).setDemoAccount(a);if(!mounted)return;setState(()=>_switching=false);if(a.role.name=='seller'){context.go('/seller/dashboard');}else{context.go('/');}}
  @override Widget build(BuildContext context){final accounts=DemoAccounts.forModule(_module);final records=DemoRuntime.state.forModule(_module);final session=ref.watch(authSessionProvider);final stage=DemoRuntime.state.stageFor(_module);return Scaffold(appBar:AppBar(title:const Text('ASKODOX Demo Center')),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:800),child:ListView(padding:const EdgeInsets.all(16),children:[
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('DEMO ONLY',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Uses dummy Party A and Party B accounts to demonstrate the existing ASKODOX workflow. No real payments or customer leads.'),const SizedBox(height:12),SelectableText('Common demo password: ${DemoAccounts.demoPassword}'),if(session.tokenPlaceholder=='DEMO_ONLY'&&session.user!=null)...[const SizedBox(height:10),Text('Current demo session: ${session.user!.displayName??session.user!.id}',style:const TextStyle(fontWeight:FontWeight.w600))]]))),
    const SizedBox(height:12),DropdownButtonFormField<DemoModule>(value:_module,decoration:const InputDecoration(labelText:'Demo module',border:OutlineInputBorder()),items:[for(final m in DemoModule.values)DropdownMenuItem(value:m,child:Text(_moduleName(m)))],onChanged:(v)=>v==null?null:setState(()=>_module=v)),const SizedBox(height:16),
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Demo journey · ${_stageName(stage)}',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),const Text('Request → Match → Accept → Complete / History'),const SizedBox(height:12),FilledButton.icon(onPressed:stage==DemoJourneyStage.completed?null:_advance,icon:const Icon(Icons.play_arrow_rounded),label:Text(stage==DemoJourneyStage.completed?'Journey completed':'Run next demo step'))]))),
    const SizedBox(height:12),for(final a in accounts)Card(child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,10),child:Column(children:[ListTile(leading:CircleAvatar(child:Text(a.party==DemoParty.a?'A':'B')),title:Text('${a.party==DemoParty.a?'Party A':'Party B'} · ${a.displayName}'),subtitle:SelectableText('${a.loginId}\n${a.location}\n${a.sampleIntent}'),isThreeLine:true),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:_switching?null:()=>_enterAs(a),icon:const Icon(Icons.login_rounded),label:Text('Enter as ${a.party==DemoParty.a?'Party A':'Party B'}')))]))),
    const SizedBox(height:12),Text('Demo activity',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),for(final r in records)Card(child:ListTile(leading:Icon(r.party==DemoParty.a?Icons.storefront_outlined:Icons.person_search_outlined),title:Text(r.title),subtitle:Text('${r.type.name} · ${r.status}'),trailing:Text(r.party==DemoParty.a?'A':'B'))),const SizedBox(height:16),OutlinedButton.icon(onPressed:_reset,icon:const Icon(Icons.restart_alt_rounded),label:const Text('Reset all demo data'))]))));}
}
