import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../application/admin_controller.dart';
import '../domain/admin_models.dart';

class AdminLoginScreen extends ConsumerStatefulWidget { const AdminLoginScreen({super.key}); @override ConsumerState<AdminLoginScreen> createState() => _AdminLoginScreenState(); }
class _AdminLoginScreenState extends ConsumerState<AdminLoginScreen> {
  AdminRole role = AdminRole.superAdmin;
  @override Widget build(BuildContext context) => Scaffold(body: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: Card(child: Padding(padding: const EdgeInsets.all(28), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [Icon(Icons.admin_panel_settings, size: 54, color: Theme.of(context).colorScheme.primary), const SizedBox(height: 16), Text('PODX Admin', style: Theme.of(context).textTheme.headlineMedium, textAlign: TextAlign.center), const Text('Mock secure access • local data only', textAlign: TextAlign.center), const SizedBox(height: 24), DropdownButtonFormField<AdminRole>(value: role, isExpanded: true, decoration: const InputDecoration(labelText: 'Admin role', border: OutlineInputBorder()), selectedItemBuilder: (context) => [for (final value in AdminRole.values) Align(alignment: Alignment.centerLeft, child: Text(value.label, maxLines: 1, overflow: TextOverflow.ellipsis))], items: [for (final value in AdminRole.values) DropdownMenuItem(value: value, child: Text(value.label, maxLines: 1, overflow: TextOverflow.ellipsis))], onChanged: (value) { if (value != null) setState(() => role = value); }), const SizedBox(height: 16), FilledButton.icon(onPressed: () async { await ref.read(adminControllerProvider.notifier).login(role); if (context.mounted) context.go('/admin/dashboard'); }, icon: const Icon(Icons.login), label: const Text('Sign in'))]))))));
}

class AdminShell extends ConsumerWidget {
  const AdminShell({required this.child, super.key}); final Widget child;
  @override Widget build(BuildContext context, WidgetRef ref) {
    final user = ref.watch(adminControllerProvider).user;
    if (user == null) return const AdminLoginScreen();
    final allowed = sectionsFor(user.role).toList();
    final location = GoRouterState.of(context).uri.pathSegments.last;
    final current = allowed.indexWhere((e) => e.name == location);
    final destinations = [for (final section in allowed) NavigationRailDestination(icon: Icon(_icon(section)), label: Text(_label(section)))];
    return LayoutBuilder(builder: (context, constraints) { final wide = constraints.maxWidth >= 850; return Scaffold(appBar: AppBar(title: Text('PODX Admin • ${user.role.label}'), actions: [IconButton(tooltip:'Analytics and BI',onPressed:()=>context.push('/admin/analytics'),icon:const Icon(Icons.analytics_outlined)),IconButton(tooltip:'Report builder',onPressed:()=>context.push('/admin/reports'),icon:const Icon(Icons.summarize_outlined)),if (!wide) PopupMenuButton<AdminSection>(icon: const Icon(Icons.menu), onSelected: (s) => context.go('/admin/${s.name}'), itemBuilder: (_) => [for (final s in allowed) PopupMenuItem(value: s, child: Text(_label(s)))]), IconButton(tooltip: 'Sign out', onPressed: () => context.go('/admin/login'), icon: const Icon(Icons.logout))]), body: Row(children: [if (wide) NavigationRail(extended: constraints.maxWidth >= 1150, selectedIndex: current < 0 ? 0 : current, onDestinationSelected: (i) => context.go('/admin/${allowed[i].name}'), destinations: destinations), if (wide) const VerticalDivider(width: 1), Expanded(child: child)])); });
  }
  static String _label(AdminSection s) => switch(s) { AdminSection.productRequests => 'Requests', AdminSection.searchQuality => 'Search quality', AdminSection.auditLog => 'Audit Log', _ => '${s.name[0].toUpperCase()}${s.name.substring(1)}' };
  static IconData _icon(AdminSection s) => switch(s) { AdminSection.dashboard => Icons.dashboard_outlined, AdminSection.sellers => Icons.store_outlined, AdminSection.catalog => Icons.inventory_2_outlined, AdminSection.productRequests => Icons.playlist_add_check, AdminSection.searchQuality => Icons.manage_search, AdminSection.moderation => Icons.gavel_outlined, AdminSection.support => Icons.support_agent, AdminSection.auditLog => Icons.history, AdminSection.settings => Icons.settings_outlined };
}

class AdminSectionScreen extends ConsumerWidget {
  const AdminSectionScreen({required this.section, super.key}); final AdminSection section;
  @override Widget build(BuildContext context, WidgetRef ref) { final state = ref.watch(adminControllerProvider); final user = state.user; if (user != null && !sectionsFor(user.role).contains(section)) return const Center(child: Text('This role does not have access.'));
    return Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(AdminShell._label(section), style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 12), if (section != AdminSection.dashboard && section != AdminSection.auditLog && section != AdminSection.settings) const AdminFilters(), const SizedBox(height: 12), Expanded(child: _content(context, ref, state))])); }
  Widget _content(BuildContext context, WidgetRef ref, AdminState state) => switch(section) {
    AdminSection.dashboard => GridView.builder(gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 260, mainAxisExtent: 130, crossAxisSpacing: 12, mainAxisSpacing: 12), itemCount: state.metrics.values.length, itemBuilder: (_, i) { final e = state.metrics.values.entries.elementAt(i); return Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(e.key), const Spacer(), Text('${e.value}', style: Theme.of(context).textTheme.headlineMedium)]))); }),
    AdminSection.sellers => ListView(children: [for (final s in state.sellers) Card(child: ListTile(isThreeLine: true, leading: const CircleAvatar(child: Icon(Icons.store)), title: Text(s.shopName), subtitle: Text('${s.ownerName} • ${s.mobile}\n${s.category} • ${s.address} • ${s.coordinates}\nRegistered ${s.registeredAt.toLocal().toString().split(' ').first} • ${s.status.name}\nDocuments: ${s.shopPhotoRef}, ${s.businessDocumentRef}'), trailing: PopupMenuButton<String>(onSelected: (v) => _sellerAction(context, ref, s, v), itemBuilder: (_) => const [PopupMenuItem(value: 'approve', child: Text('Approve')), PopupMenuItem(value: 'reject', child: Text('Reject')), PopupMenuItem(value: 'more', child: Text('Request information')), PopupMenuItem(value: 'suspend', child: Text('Suspend')), PopupMenuItem(value: 'restore', child: Text('Restore'))])))]),
    AdminSection.catalog => ListView(children: [for (final p in state.catalog) Card(child: ListTile(leading: const Icon(Icons.image_outlined), title: Text(p.name), subtitle: Text('${p.brand} • ${p.category} / ${p.subcategory}\n${p.variant} • ${p.packSize} • ${p.status.name}\nKeywords: ${p.searchKeywords.join(', ')}'), trailing: const Icon(Icons.edit_outlined))) ]),
    AdminSection.productRequests => ListView(children: [for (final r in state.requests) Card(child: ListTile(isThreeLine: true, leading: const Icon(Icons.add_photo_alternate_outlined), title: Text(r.name), subtitle: Text('${r.category} • demand ${r.demandScore}\nBuyers ${r.buyerRequests} • Sellers ${r.sellerRequests} • ${r.location}\nSimilar: ${r.similarMatches.join(', ')} • ${r.status.name}'), trailing: Wrap(children: [IconButton(tooltip: 'Approve and add', icon: const Icon(Icons.check_circle_outline), onPressed: () => ref.read(adminControllerProvider.notifier).approveRequest(r.id)), IconButton(tooltip: 'Link duplicate', icon: const Icon(Icons.link), onPressed: state.catalog.isEmpty ? null : () => ref.read(adminControllerProvider.notifier).linkDuplicate(r.id, state.catalog.first.id))]))) ]),
    AdminSection.searchQuality => ListView(children: const [
      _SearchIssue(title: 'Failed search terms', detail: 'protein powder (12), millet pasta (8)', icon: Icons.search_off),
      _SearchIssue(title: 'Frequently requested products', detail: 'Organic jaggery (24), USB-C cable 2m (19)', icon: Icons.add_shopping_cart),
      _SearchIssue(title: 'Barcode conflicts', detail: '89099999 maps to 2 coffee products', icon: Icons.qr_code_2),
      _SearchIssue(title: 'OCR conflicts', detail: '“Classic Brew” has 2 possible catalog matches', icon: Icons.document_scanner),
      _SearchIssue(title: 'Image match failures', detail: '3 local demo requests need review', icon: Icons.image_not_supported),
    ]),
    AdminSection.moderation => ListView(children: [for (final m in state.moderation) Card(child: ListTile(isThreeLine: true, title: Text(m.product), subtitle: Text('${m.seller} • ${m.type.name}\nReported ₹${m.reportedPrice} • Listed ₹${m.currentPrice}\n${m.reporterNote} • Evidence: ${m.evidenceRef} • ${m.status.name}'), trailing: PopupMenuButton<ModerationAction>(onSelected: (a) => ref.read(adminControllerProvider.notifier).moderate(m.id, a, reason: a == ModerationAction.suspendSeller ? 'Policy violation' : ''), itemBuilder: (_) => [for (final a in ModerationAction.values) PopupMenuItem(value: a, child: Text(a.name))]))) ]),
    AdminSection.support => ListView(children: [for (final c in state.support) Card(child: ListTile(title: Text(c.subject), subtitle: Text('${c.type} • ${c.priority.name} • ${c.status.name}\nAssigned: ${c.assignee ?? 'Unassigned'}'), trailing: PopupMenuButton<SupportStatus>(onSelected: (s) => ref.read(adminControllerProvider.notifier).updateSupport(c.id, status: s), itemBuilder: (_) => [for (final s in SupportStatus.values) PopupMenuItem(value: s, child: Text(s.name))]))) ]),
    AdminSection.auditLog => state.audit.isEmpty ? const Center(child: Text('No admin actions yet. Audit entries are immutable.')) : ListView(children: [for (final a in state.audit) ListTile(leading: const Icon(Icons.lock_clock), title: Text(a.action), subtitle: Text('${a.adminRole.label} • ${a.entityType}: ${a.entity}\n${a.previousStatus} → ${a.newStatus} • ${a.reason}\n${a.timestamp.toLocal()}'))]),
    AdminSection.settings => const Center(child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.security, size: 48), SizedBox(height: 12), Text('Security-ready architecture'), Text('Mock authentication • document references only • immutable audit trail')])) };
  Future<void> _sellerAction(BuildContext context, WidgetRef ref, SellerVerificationCase seller, String action) async { final target = switch(action) {'approve' => SellerVerificationStatus.approved, 'reject' => SellerVerificationStatus.rejected, 'more' => SellerVerificationStatus.moreInformation, 'suspend' => SellerVerificationStatus.suspended, _ => SellerVerificationStatus.approved}; String reason = ''; if (action == 'reject' || action == 'suspend') { reason = await _reason(context) ?? ''; if (reason.trim().isEmpty) return; } ref.read(adminControllerProvider.notifier).updateSeller(seller.id, target, reason: reason); }
  Future<String?> _reason(BuildContext context) { final controller = TextEditingController(); return showDialog<String>(context: context, builder: (context) => AlertDialog(title: const Text('Reason required'), content: TextField(controller: controller, autofocus: true, decoration: const InputDecoration(labelText: 'Internal reason')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, controller.text), child: const Text('Confirm'))])); }
}

class AdminFilters extends StatelessWidget { const AdminFilters({super.key}); @override Widget build(BuildContext context) => SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children: [for (final label in const ['Date range', 'Status', 'Category', 'Seller verification', 'Report type', 'Priority', 'Demand level']) Padding(padding: const EdgeInsets.only(right: 8), child: FilterChip(label: Text(label), selected: false, onSelected: (_) {}))])); }
class _SearchIssue extends StatelessWidget { const _SearchIssue({required this.title,required this.detail,required this.icon}); final String title,detail; final IconData icon; @override Widget build(BuildContext context)=>Card(child:ListTile(leading:Icon(icon),title:Text(title),subtitle:Text(detail),trailing:const Chip(label:Text('Mock data')))); }
