import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../generated/l10n/app_localizations.dart';
import '../application/monetization_controller.dart';
import '../domain/monetization_models.dart';

class AdminMonetizationScreen extends ConsumerStatefulWidget { const AdminMonetizationScreen({super.key}); @override ConsumerState<AdminMonetizationScreen> createState()=>_State(); }
class _State extends ConsumerState<AdminMonetizationScreen> { SubscriptionStatus? filter; @override Widget build(BuildContext context){final l=AppLocalizations.of(context)!;final state=ref.watch(monetizationControllerProvider);final metrics=[(l.mrr,'₹18,240'),(l.arr,'₹2,18,880'),(l.activePaidSellers,'42'),(l.trialSellers,'11'),(l.conversionRate,'18%'),(l.failedPayments,'3'),(l.cancelledSubscriptions,'4')];return Scaffold(appBar:AppBar(title:Text(l.subscriptionManagement)),body:ListView(padding:const EdgeInsets.all(16),children:[Card(color:Theme.of(context).colorScheme.secondaryContainer,child:ListTile(leading:const Icon(Icons.science_outlined),title:Text(l.demoRevenueData),subtitle:Text(l.noRealBilling))),Wrap(spacing:8,children:[for(final m in metrics)SizedBox(width:180,child:Card(child:ListTile(title:Text(m.$1),subtitle:Text(m.$2,style:Theme.of(context).textTheme.headlineSmall))))]),Text(l.revenueByPlan,style:Theme.of(context).textTheme.titleLarge),const ListTile(title:Text('Starter • ₹5,980')),const ListTile(title:Text('Growth • ₹7,990')),const ListTile(title:Text('Pro • ₹4,270')),Text(l.revenueTrend,style:Theme.of(context).textTheme.titleLarge),const LinearProgressIndicator(value:.72),DropdownButtonFormField<SubscriptionStatus?>(value:filter,decoration:InputDecoration(labelText:l.filterStatus),items:[DropdownMenuItem(value:null,child:Text(l.allStatuses)),for(final s in SubscriptionStatus.values)DropdownMenuItem(value:s,child:Text(s.name))],onChanged:(v)=>setState(()=>filter=v)),if(filter==null||filter==state.subscription.status)Card(child:ListTile(isThreeLine:true,title:const Text('Demo Seller'),subtitle:Text('${state.currentPlan.name} • ${state.subscription.status.name}\n${l.paymentStatus}: ${state.payment?.status.name ?? l.noPaymentAttempt}'),trailing:PopupMenuButton<String>(onSelected:(action)=>_action(action),itemBuilder:(_)=>[PopupMenuItem(value:'change',child:Text(l.changePlan)),PopupMenuItem(value:'trial',child:Text(l.grantTrial)),PopupMenuItem(value:'extend',child:Text(l.extendTrial)),PopupMenuItem(value:'cancel',child:Text(l.cancelPlan)),PopupMenuItem(value:'discount',child:Text(l.manualDiscount)),PopupMenuItem(value:'received',child:Text(l.markPaymentReceived)),PopupMenuItem(value:'refund',child:Text(l.mockRefund))]))),Text(l.paymentFailures,style:Theme.of(context).textTheme.titleLarge),Text(state.payment?.status==PaymentStatus.failed?l.paymentFailed:l.noPaymentFailures)]));}
 Future<void> _action(String action) async {final l=AppLocalizations.of(context)!;final reason=await _reason(l);if(reason==null||reason.trim().isEmpty)return;final c=ref.read(monetizationControllerProvider.notifier);if(action=='change'){await c.adminChangePlan('growth',reason);}else if(action=='trial'){try{await c.adminGrantTrial('starter',reason);}on StateError{if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(l.trialUnavailable)));}}else if(action=='cancel'){await c.cancel();}else{if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(l.demoActionRecorded)));}}
 Future<String?> _reason(AppLocalizations l){final c=TextEditingController();return showDialog<String>(context:context,builder:(context)=>AlertDialog(title:Text(l.adminReasonRequired),content:TextField(controller:c,decoration:InputDecoration(labelText:l.adminReason)),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text(l.cancel)),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:Text(l.confirm))]));}}
