import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../generated/l10n/app_localizations.dart';
import '../application/monetization_controller.dart';
import '../domain/monetization_models.dart';

String money(int value) => '₹${value.toString()}';
bool _te(BuildContext context) => Localizations.localeOf(context).languageCode == 'te';
String _cycle(BuildContext context, BillingCycle value) => _te(context) ? (value == BillingCycle.monthly ? 'నెలవారీ' : 'వార్షిక') : value.name;
String _subscriptionStatus(BuildContext context, SubscriptionStatus value) => _te(context) ? switch (value) { SubscriptionStatus.active => 'యాక్టివ్', SubscriptionStatus.cancelled => 'రద్దు చేయబడింది', _ => value.name } : value.name;
String _trialStatus(BuildContext context, TrialStatus value) => _te(context) ? switch (value) { TrialStatus.eligible => 'అర్హత ఉంది', _ => value.name } : value.name;
String _invoiceStatus(BuildContext context, dynamic value) { final name = value.name.toString(); if (!_te(context)) return name; return switch (name) { 'paid' => 'చెల్లించబడింది', 'pending' => 'పెండింగ్', 'failed' => 'విఫలమైంది', 'refunded' => 'రిఫండ్ చేయబడింది', _ => name }; }
String _visibility(BuildContext context, String value) { if (!_te(context)) return value; return switch (value.toLowerCase()) { 'local' => 'లోకల్', 'regional' => 'ప్రాంతీయ', 'national' => 'దేశవ్యాప్తంగా', 'basic' => 'బేసిక్', 'standard' => 'స్టాండర్డ్', 'priority' => 'ప్రాధాన్యత', _ => value }; }
String _support(BuildContext context, String value) { if (!_te(context)) return value; return switch (value.toLowerCase()) { 'basic' => 'బేసిక్', 'standard' => 'స్టాండర్డ్', 'priority' => 'ప్రాధాన్యత', 'premium' => 'ప్రీమియం', _ => value }; }
class PricingScreen extends ConsumerWidget { const PricingScreen({super.key});
  @override Widget build(BuildContext context, WidgetRef ref) { final l = AppLocalizations.of(context)!; final state = ref.watch(monetizationControllerProvider); return Scaffold(appBar: AppBar(title: Text(l.sellerPlans), actions: [TextButton(onPressed: () => context.push('/seller/plans/compare'), child: Text(l.comparePlans))]), body: ListView(padding: const EdgeInsets.all(16), children: [Card(color: Theme.of(context).colorScheme.secondaryContainer, child: ListTile(leading: const Icon(Icons.science_outlined), title: Text(l.demoPricing), subtitle: Text(l.noRealBilling))), SegmentedButton<BillingCycle>(segments: [ButtonSegment(value: BillingCycle.monthly, label: Text(l.monthly)), ButtonSegment(value: BillingCycle.annual, label: Text(l.annual))], selected: {state.cycle}, onSelectionChanged: (v) { final plan = state.selectedPlan ?? state.currentPlan; ref.read(monetizationControllerProvider.notifier).selectPlan(plan, v.first); }), for (final plan in state.plans) _PlanCard(plan: plan, state: state)])); }
}
class _PlanCard extends ConsumerWidget { const _PlanCard({required this.plan, required this.state}); final SellerPlan plan; final MonetizationState state;
 @override Widget build(BuildContext context, WidgetRef ref) { final l = AppLocalizations.of(context)!; final current = plan.id == state.subscription.planId; return Card(key: ValueKey('plan-${plan.id}'), child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text(plan.name, style: Theme.of(context).textTheme.headlineSmall)), if (current) Chip(label: Text(l.currentPlan))]), Text('${money(plan.price(state.cycle))} / ${state.cycle == BillingCycle.monthly ? l.month : l.year}', style: Theme.of(context).textTheme.titleLarge), if (state.cycle == BillingCycle.annual && plan.annualSavings > 0) Chip(label: Text(l.saveAmount(money(plan.annualSavings)))), Text(l.productLimit(plan.limits.activeListings)), Text('${l.shopVisibility}: ${_visibility(context, plan.visibility)}'), ...plan.features.take(4).map((e) => ListTile(dense: true, contentPadding: EdgeInsets.zero, leading: const Icon(Icons.check), title: Text(e.description))), Row(children: [if (!current && plan.id != 'free') Expanded(child: FilledButton(onPressed: () { ref.read(monetizationControllerProvider.notifier).selectPlan(plan, state.cycle); context.push('/seller/plans/review'); }, child: Text(l.upgradePlan))), if (!current && plan.id == 'free') Expanded(child: OutlinedButton(onPressed: () => ref.read(monetizationControllerProvider.notifier).downgrade(plan.id), child: Text(l.downgrade))), if (current && state.subscription.status == SubscriptionStatus.cancelled) Expanded(child: FilledButton(onPressed: () => ref.read(monetizationControllerProvider.notifier).reactivate(), child: Text(l.reactivate))), if (current && plan.id != 'free' && state.subscription.status != SubscriptionStatus.cancelled) Expanded(child: TextButton(onPressed: () => ref.read(monetizationControllerProvider.notifier).cancel(), child: Text(l.cancelPlan)))]), if (!current && plan.trialDays > 0 && state.subscription.trialStatus == TrialStatus.eligible) TextButton(onPressed: () => ref.read(monetizationControllerProvider.notifier).activateTrial(plan.id), child: Text(l.startFreeTrial(plan.trialDays)))]))); }
}
class PlanComparisonScreen extends ConsumerWidget { const PlanComparisonScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final l = AppLocalizations.of(context)!; final plans = ref.watch(monetizationControllerProvider).plans; final rows = <(String, String Function(SellerPlan))>[(l.productListings, (p) => '${p.limits.activeListings}'), (l.shopVisibility, (p) => _visibility(context,p.visibility)), (l.buyerRequestAccess, (p) => '${p.limits.buyerRequestResponses}'), (l.demandAnalytics, (p) => '${p.limits.analyticsHistoryDays} ${l.days}'), (l.priceAlerts, (p) => p.id == 'free' ? l.basic : l.included), (l.promotionalOffers, (p) => '${p.limits.offerCampaigns}'), (l.featuredPlacement, (p) => p.features.any((e) => e.entitlement == FeatureEntitlement.featuredPlacement) ? l.included : '—'), (l.supportLevel, (p) => _support(context,p.supportLevel)), (l.multiShop, (p) => '${p.limits.shopLocations}')]; return Scaffold(appBar: AppBar(title: Text(l.comparePlans)), body: SingleChildScrollView(scrollDirection: Axis.horizontal, child: DataTable(columns: [DataColumn(label: Text(l.feature)), for (final p in plans) DataColumn(label: Text(p.name))], rows: [for (final row in rows) DataRow(cells: [DataCell(Text(row.$1)), for (final p in plans) DataCell(Text(row.$2(p)))])]))); } }
class UsageScreen extends ConsumerWidget { const UsageScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final l = AppLocalizations.of(context)!; final state = ref.watch(monetizationControllerProvider); final limits = state.currentPlan.limits; final items = [(l.activeListings, state.usage.activeListings, limits.activeListings), (l.offers, state.usage.offers, limits.offerCampaigns), (l.requestResponses, state.usage.buyerRequestResponses, limits.buyerRequestResponses), (l.shopCount, state.usage.shopLocations, limits.shopLocations)]; return Scaffold(appBar: AppBar(title: Text(l.sellerUsage)), body: ListView(padding: const EdgeInsets.all(16), children: [for (final item in items) Card(child: ListTile(title: Text(item.$1), subtitle: LinearProgressIndicator(value: item.$3 == 0 ? 1.0 : (item.$2/item.$3).clamp(0,1).toDouble()), trailing: Text('${item.$2} / ${item.$3}'), isThreeLine: true)), ListTile(title: Text(l.analyticsAccess), subtitle: Text(l.historyDays(limits.analyticsHistoryDays))), ListTile(title: Text(l.storageUsage), subtitle: Text(l.placeholder)), if (!ref.read(monetizationControllerProvider.notifier).limit('listings').allowed) Card(color: Theme.of(context).colorScheme.errorContainer, child: ListTile(title: Text(l.limitReached), subtitle: Text(l.limitExplanation(state.usage.activeListings, limits.activeListings)), trailing: FilledButton(onPressed: () => context.push('/seller/plans'), child: Text(l.upgradePlan))))])); } }
class SubscriptionScreen extends ConsumerWidget { const SubscriptionScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final l=AppLocalizations.of(context)!; final s=ref.watch(monetizationControllerProvider); final sub=s.subscription; String date(DateTime d)=>'${d.day}/${d.month}/${d.year}'; return Scaffold(appBar: AppBar(title: Text(l.currentSubscription)), body: ListView(padding: const EdgeInsets.all(16), children: [ListTile(title: Text(l.currentPlan), subtitle: Text(s.currentPlan.name)), ListTile(title: Text(l.billingCycle), subtitle: Text(_cycle(context,sub.billingCycle))), ListTile(title: Text(l.subscriptionStatus), subtitle: Text(_subscriptionStatus(context,sub.status))), ListTile(title: Text(l.startDate), subtitle: Text(date(sub.startDate))), ListTile(title: Text(l.renewalDate), subtitle: Text(date(sub.renewalDate))), ListTile(title: Text(l.trialStatus), subtitle: Text('${_trialStatus(context,sub.trialStatus)} • ${sub.trialDaysRemaining} ${l.days}')), SwitchListTile(value: sub.autoRenew, onChanged: null, title: Text(l.autoRenew)), ListTile(title: Text(l.paymentMethod), subtitle: Text(sub.paymentMethodLabel)), if (sub.pendingPlanId != null) ListTile(title: Text(l.downgradeScheduled), subtitle: Text('${sub.pendingPlanId} • ${l.nextRenewal}')), FilledButton.tonal(onPressed: () => context.push('/seller/invoices'), child: Text(l.invoiceHistory)), OutlinedButton(onPressed: () {}, child: Text(l.restorePurchase))])); } }
class OrderReviewScreen extends ConsumerStatefulWidget { const OrderReviewScreen({super.key}); @override ConsumerState<OrderReviewScreen> createState()=>_OrderReviewState(); }
class _OrderReviewState extends ConsumerState<OrderReviewScreen> { final promo=TextEditingController(); @override Widget build(BuildContext context) { final l=AppLocalizations.of(context)!; final s=ref.watch(monetizationControllerProvider); final p=s.selectedPlan; if(p==null)return Scaffold(body: Center(child: Text(l.planUnavailable))); return Scaffold(appBar: AppBar(title: Text(l.reviewOrder)), body: ListView(padding: const EdgeInsets.all(20), children: [ListTile(title: Text(p.name), subtitle: Text(_cycle(context,s.cycle)), trailing: Text(money(p.price(s.cycle)))), TextField(controller: promo, decoration: InputDecoration(labelText: l.promoCode, suffixIcon: IconButton(onPressed: ()=>ref.read(monetizationControllerProvider.notifier).applyPromo(promo.text), icon: const Icon(Icons.check)))), if(s.promo!=null) Text(s.promo!.isValid?l.promoApplied:l.promoInvalid), const SizedBox(height: 20), FilledButton(onPressed: ()=>context.push('/seller/plans/payment'), child: Text(l.continueToDemoPayment))])); } }
class PaymentScreen extends ConsumerStatefulWidget { const PaymentScreen({super.key}); @override ConsumerState<PaymentScreen> createState()=>_PaymentState(); }
class _PaymentState extends ConsumerState<PaymentScreen> { PaymentMethodType method=PaymentMethodType.upi; @override Widget build(BuildContext context) { final l=AppLocalizations.of(context)!; final s=ref.watch(monetizationControllerProvider); return Scaffold(appBar: AppBar(title: Text(l.demoPayment)), body: ListView(padding: const EdgeInsets.all(20), children: [Card(color: Theme.of(context).colorScheme.tertiaryContainer, child: ListTile(leading: const Icon(Icons.warning_amber), title: Text(l.demoPaymentOnly), subtitle: Text(l.noPaymentDetails))), for(final value in PaymentMethodType.values) RadioListTile(value:value, groupValue:method, onChanged:(v)=>setState(()=>method=v!), title:Text(switch(value){PaymentMethodType.upi=>l.upi,PaymentMethodType.card=>l.card,PaymentMethodType.netBanking=>l.netBanking,PaymentMethodType.wallet=>l.wallet})), FilledButton(onPressed:s.busy?null:() async { final r=await ref.read(monetizationControllerProvider.notifier).pay(method); if(mounted) _result(r); }, child:Text(l.confirmDemoPayment)), TextButton(onPressed:s.busy?null:() async { final r=await ref.read(monetizationControllerProvider.notifier).pay(method,simulateFailure:true); if(mounted) _result(r); }, child:Text(l.simulateFailure))])); } void _result(PaymentAttempt result){ final l=AppLocalizations.of(context)!; if(result.status==PaymentStatus.successful){ showDialog(context:context,builder:(_)=>AlertDialog(title:Text(l.paymentSuccessful),content:Text(l.entitlementsRefreshed),actions:[TextButton(onPressed:(){Navigator.pop(context);context.go('/seller/subscription');},child:Text(l.done))])); }else{ showDialog(context:context,builder:(_)=>AlertDialog(title:Text(l.paymentFailed),content:Text(l.paymentFailureHelp),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text(l.retryPayment)),TextButton(onPressed:(){Navigator.pop(context);context.go('/seller/plans');},child:Text(l.continueFree))])); }} }
class InvoiceHistoryScreen extends ConsumerWidget { const InvoiceHistoryScreen({super.key}); @override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!;return Scaffold(appBar:AppBar(title:Text(l.invoiceHistory)),body:FutureBuilder<List<Invoice>>(future:ref.read(invoiceRepositoryProvider).invoicesFor('seller-demo'),builder:(context,snapshot){final data=snapshot.data;if(data==null)return const Center(child:CircularProgressIndicator());if(data.isEmpty)return Center(child:Text(l.noInvoices));return ListView(children:[Card(color:Theme.of(context).colorScheme.secondaryContainer,child:ListTile(title:Text(l.gstPlaceholder),subtitle:Text(l.notTaxCompliant))),for(final i in data)ListTile(isThreeLine:true,title:Text(i.number),subtitle:Text('${i.planName} • ${i.period}\n${l.taxPlaceholder}: ${money(i.taxPlaceholder)} • ${_invoiceStatus(context,i.status)} • ${i.date.day}/${i.date.month}/${i.date.year}'),trailing:Column(children:[Text(money(i.total)),IconButton(tooltip:l.downloadPlaceholder,onPressed:()=>ref.read(invoiceRepositoryProvider).requestDownload(i.number),icon:const Icon(Icons.download_outlined))]))]);}));} }