import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/providers/backend_providers.dart';
import '../../../core/providers/offline_providers.dart';
import '../../../core/sync/sync_models.dart';
import '../../../generated/l10n/app_localizations.dart';

class SyncStatusScreen extends ConsumerStatefulWidget { const SyncStatusScreen({super.key}); @override ConsumerState<SyncStatusScreen> createState() => _State(); }
class _State extends ConsumerState<SyncStatusScreen> {
  @override Widget build(BuildContext context) { final l = AppLocalizations.of(context)!; final sync = ref.watch(syncServiceProvider); final status = sync.status; final connection = ref.watch(connectivityStatusProvider).valueOrNull; return Scaffold(appBar: AppBar(title: Text(l.syncStatus)), body: RefreshIndicator(onRefresh: () async { await sync.sync(); setState(() {}); }, child: ListView(padding: const EdgeInsets.all(24), children: [Text('${l.pendingChanges}: ${status.pendingCount}'), Text('${l.failedChanges}: ${status.failedCount}'), Text('${l.connectionState}: ${connection?.name ?? 'unknown'}'), Text('${l.lastSuccessfulSync}: ${status.lastSyncedAt?.toIso8601String() ?? l.never}'), const SizedBox(height: 16), FilledButton.icon(onPressed: () async { await sync.sync(); if (mounted) setState(() {}); }, icon: const Icon(Icons.sync), label: Text(l.syncNow)), TextButton(onPressed: () async { await sync.clearCompleted(); setState(() {}); }, child: Text(l.clearCompletedHistory)), const Divider(), if (sync.queue.isEmpty) Center(child: Padding(padding: const EdgeInsets.all(32), child: Text(l.noPendingChanges))), for (final item in sync.queue) Card(key: ValueKey(item.id), child: ListTile(title: Text(item.change.entityType), subtitle: Text('${item.change.operation} • ${item.status.name}${item.failureReason == null ? '' : '\n${item.failureReason}'}'), isThreeLine: item.failureReason != null, trailing: Wrap(children: [if (item.status == SyncItemStatus.failed) IconButton(tooltip: l.retry, onPressed: () async { await sync.retry(item.id); setState(() {}); }, icon: const Icon(Icons.refresh)), if (item.status == SyncItemStatus.conflict) IconButton(tooltip: l.viewConflict, onPressed: () => context.push('/conflict/${item.id}'), icon: const Icon(Icons.compare_arrows)), IconButton(tooltip: l.remove, onPressed: () async { await sync.remove(item.id); setState(() {}); }, icon: const Icon(Icons.delete_outline))]))) ]))); }
}

class ConflictResolutionScreen extends StatefulWidget { const ConflictResolutionScreen({required this.itemId, super.key}); final String itemId; @override State<ConflictResolutionScreen> createState() => _ConflictResolutionScreenState(); }
class _ConflictResolutionScreenState extends State<ConflictResolutionScreen> {
  ConflictResolutionStrategy strategy = ConflictResolutionStrategy.keepLocal;
  @override Widget build(BuildContext context) { final l = AppLocalizations.of(context)!; return Scaffold(appBar: AppBar(title: Text(l.resolveConflict)), body: ListView(padding: const EdgeInsets.all(20), children: [Text(l.priceConflictExample, style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 16), Card(child: ListTile(title: Text(l.localValue), subtitle: const Text('₹120 • 10:30'))), Card(child: ListTile(title: Text(l.remoteValue), subtitle: const Text('₹125 • 10:32'))), ListTile(title: Text(l.recommendedAction), subtitle: Text(l.keepLatestValue)), DropdownButtonFormField(value: strategy, items: ConflictResolutionStrategy.values.map((value) => DropdownMenuItem(value: value, child: Text(value.name))).toList(), onChanged: (value) => setState(() => strategy = value!), decoration: InputDecoration(labelText: l.resolution)), const SizedBox(height: 20), FilledButton(onPressed: () => Navigator.pop(context), child: Text(l.applyResolution))])); }
}
